<?php

/**
 * Generated by PHPUnit_SkeletonGenerator 1.2.1 on 2014-08-09 at 08:20:25.
 */
class DatabaseConnectionTest extends PHPUnit_Framework_TestCase {

    /**
     * @var DatabaseConnection
     */
    protected $object;

    /**
     * Sets up the fixture, for example, opens a network connection.
     * This method is called before a test is executed.
     */
    protected function setUp() {
        $this->object = new DatabaseConnection;
    }

    /**
     * Tears down the fixture, for example, closes a network connection.
     * This method is called after a test is executed.
     */
    protected function tearDown() {
        
    }

    /**
     * @covers DatabaseConnection::OpenConnection
     * @todo   Implement testOpenConnection().
     */
    public function testOpenConnection() {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
                'This test has not been implemented yet.'
        );
    }

    /**
     * @covers DatabaseConnection::_connect
     * @todo   Implement test_connect().
     */
    public function test_connect() {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
                'This test has not been implemented yet.'
        );
    }

    /**
     * @covers DatabaseConnection::_disconnect
     * @todo   Implement test_disconnect().
     */
    public function test_disconnect() {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
                'This test has not been implemented yet.'
        );
    }

    /**
     * @covers DatabaseConnection::Destructor
     * @todo   Implement testDestructor().
     */
    public function testDestructor() {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
                'This test has not been implemented yet.'
        );
    }

    /**
     * @covers DatabaseConnection::Create
     * @todo   Implement testCreate().
     */
    public function testCreate() {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
                'This test has not been implemented yet.'
        );
    }

    /**
     * @covers DatabaseConnection::Query
     * @todo   Implement testQuery().
     */
    public function testQuery() {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
                'This test has not been implemented yet.'
        );
    }

    /**
     * @covers DatabaseConnection::MultiQuery
     * @todo   Implement testMultiQuery().
     */
    public function testMultiQuery() {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
                'This test has not been implemented yet.'
        );
    }

    /**
     * @covers DatabaseConnection::Identity
     * @todo   Implement testIdentity().
     */
    public function testIdentity() {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
                'This test has not been implemented yet.'
        );
    }

    /**
     * @covers DatabaseConnection::AffectedRows
     * @todo   Implement testAffectedRows().
     */
    public function testAffectedRows() {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
                'This test has not been implemented yet.'
        );
    }

    /**
     * @covers DatabaseConnection::FoundRows
     * @todo   Implement testFoundRows().
     */
    public function testFoundRows() {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
                'This test has not been implemented yet.'
        );
    }

    /**
     * @covers DatabaseConnection::_log_query
     * @todo   Implement test_log_query().
     */
    public function test_log_query() {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
                'This test has not been implemented yet.'
        );
    }

}
