<?php

/**
 * Generated by PHPUnit_SkeletonGenerator 1.2.1 on 2014-08-09 at 08:20:24.
 */
class JsHttpRequestTest extends PHPUnit_Framework_TestCase {

    /**
     * @var JsHttpRequest
     */
    protected $object;

    /**
     * Sets up the fixture, for example, opens a network connection.
     * This method is called before a test is executed.
     */
    protected function setUp() {
        $this->object = new JsHttpRequest;
    }

    /**
     * Tears down the fixture, for example, closes a network connection.
     * This method is called after a test is executed.
     */
    protected function tearDown() {
        
    }

    /**
     * @covers JsHttpRequest::isActive
     * @todo   Implement testIsActive().
     */
    public function testIsActive() {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
                'This test has not been implemented yet.'
        );
    }

    /**
     * @covers JsHttpRequest::getJsCode
     * @todo   Implement testGetJsCode().
     */
    public function testGetJsCode() {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
                'This test has not been implemented yet.'
        );
    }

    /**
     * @covers JsHttpRequest::setEncoding
     * @todo   Implement testSetEncoding().
     */
    public function testSetEncoding() {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
                'This test has not been implemented yet.'
        );
    }

    /**
     * @covers JsHttpRequest::quoteInput
     * @todo   Implement testQuoteInput().
     */
    public function testQuoteInput() {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
                'This test has not been implemented yet.'
        );
    }

    /**
     * @covers JsHttpRequest::php2js
     * @todo   Implement testPhp2js().
     */
    public function testPhp2js() {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
                'This test has not been implemented yet.'
        );
    }

    /**
     * @covers JsHttpRequest::_correctSuperglobals
     * @todo   Implement test_correctSuperglobals().
     */
    public function test_correctSuperglobals() {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
                'This test has not been implemented yet.'
        );
    }

    /**
     * @covers JsHttpRequest::_obHandler
     * @todo   Implement test_obHandler().
     */
    public function test_obHandler() {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
                'This test has not been implemented yet.'
        );
    }

    /**
     * @covers JsHttpRequest::_toUtf8_callback
     * @todo   Implement test_toUtf8_callback().
     */
    public function test_toUtf8_callback() {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
                'This test has not been implemented yet.'
        );
    }

    /**
     * @covers JsHttpRequest::_ucs2EntitiesDecode
     * @todo   Implement test_ucs2EntitiesDecode().
     */
    public function test_ucs2EntitiesDecode() {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
                'This test has not been implemented yet.'
        );
    }

    /**
     * @covers JsHttpRequest::_ucs2EntitiesDecodeCallback
     * @todo   Implement test_ucs2EntitiesDecodeCallback().
     */
    public function test_ucs2EntitiesDecodeCallback() {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
                'This test has not been implemented yet.'
        );
    }

    /**
     * @covers JsHttpRequest::_unicodeConv
     * @todo   Implement test_unicodeConv().
     */
    public function test_unicodeConv() {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
                'This test has not been implemented yet.'
        );
    }

    /**
     * @covers JsHttpRequest::_decUcs2Decode
     * @todo   Implement test_decUcs2Decode().
     */
    public function test_decUcs2Decode() {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
                'This test has not been implemented yet.'
        );
    }

}
