<?php

/**
 * Generated by PHPUnit_SkeletonGenerator 1.2.1 on 2014-08-09 at 08:20:21.
 */
class CountQueryBuilderTest extends PHPUnit_Framework_TestCase {

    /**
     * @var CountQueryBuilder
     */
    protected $object;

    /**
     * Sets up the fixture, for example, opens a network connection.
     * This method is called before a test is executed.
     */
    protected function setUp() {
        $this->object = new CountQueryBuilder;
    }

    /**
     * Tears down the fixture, for example, closes a network connection.
     * This method is called after a test is executed.
     */
    protected function tearDown() {
        
    }

    /**
     * @covers CountQueryBuilder::Create
     * @todo   Implement testCreate().
     */
    public function testCreate() {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
                'This test has not been implemented yet.'
        );
    }

    /**
     * @covers CountQueryBuilder::Prepare
     * @todo   Implement testPrepare().
     */
    public function testPrepare() {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
                'This test has not been implemented yet.'
        );
    }

    /**
     * @covers CountQueryBuilder::_check_fields_param
     * @todo   Implement test_check_fields_param().
     */
    public function test_check_fields_param() {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
                'This test has not been implemented yet.'
        );
    }

}
