<?php

/**
 * Generated by PHPUnit_SkeletonGenerator 1.2.1 on 2014-08-09 at 08:20:20.
 */
class WaterMarkTest extends PHPUnit_Framework_TestCase {

    /**
     * @var WaterMark
     */
    protected $object;

    /**
     * Sets up the fixture, for example, opens a network connection.
     * This method is called before a test is executed.
     */
    protected function setUp() {
        $this->object = new WaterMark;
    }

    /**
     * Tears down the fixture, for example, closes a network connection.
     * This method is called after a test is executed.
     */
    protected function tearDown() {
        
    }

    /**
     * @covers WaterMark::AddWatermark
     * @todo   Implement testAddWatermark().
     */
    public function testAddWatermark() {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
                'This test has not been implemented yet.'
        );
    }

    /**
     * @covers WaterMark::_get_ave_color
     * @todo   Implement test_get_ave_color().
     */
    public function test_get_ave_color() {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
                'This test has not been implemented yet.'
        );
    }

    /**
     * @covers WaterMark::_get_image_color
     * @todo   Implement test_get_image_color().
     */
    public function test_get_image_color() {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
                'This test has not been implemented yet.'
        );
    }

}
