<?php

/**
 * Generated by PHPUnit_SkeletonGenerator 1.2.1 on 2014-08-09 at 08:18:03.
 */
class TCPDF2DBarcodeTest extends PHPUnit_Framework_TestCase {

    /**
     * @var TCPDF2DBarcode
     */
    protected $object;

    /**
     * Sets up the fixture, for example, opens a network connection.
     * This method is called before a test is executed.
     */
    protected function setUp() {
        $this->object = new TCPDF2DBarcode;
    }

    /**
     * Tears down the fixture, for example, closes a network connection.
     * This method is called after a test is executed.
     */
    protected function tearDown() {
        
    }

    /**
     * @covers TCPDF2DBarcode::getBarcodeArray
     * @todo   Implement testGetBarcodeArray().
     */
    public function testGetBarcodeArray() {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
                'This test has not been implemented yet.'
        );
    }

    /**
     * @covers TCPDF2DBarcode::getBarcodeSVG
     * @todo   Implement testGetBarcodeSVG().
     */
    public function testGetBarcodeSVG() {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
                'This test has not been implemented yet.'
        );
    }

    /**
     * @covers TCPDF2DBarcode::getBarcodeSVGcode
     * @todo   Implement testGetBarcodeSVGcode().
     */
    public function testGetBarcodeSVGcode() {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
                'This test has not been implemented yet.'
        );
    }

    /**
     * @covers TCPDF2DBarcode::getBarcodeHTML
     * @todo   Implement testGetBarcodeHTML().
     */
    public function testGetBarcodeHTML() {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
                'This test has not been implemented yet.'
        );
    }

    /**
     * @covers TCPDF2DBarcode::getBarcodePNG
     * @todo   Implement testGetBarcodePNG().
     */
    public function testGetBarcodePNG() {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
                'This test has not been implemented yet.'
        );
    }

    /**
     * @covers TCPDF2DBarcode::setBarcode
     * @todo   Implement testSetBarcode().
     */
    public function testSetBarcode() {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
                'This test has not been implemented yet.'
        );
    }

}
