<?php

/**
 * Generated by PHPUnit_SkeletonGenerator 1.2.1 on 2014-08-09 at 08:18:03.
 */
class TCPDFBarcodeTest extends PHPUnit_Framework_TestCase {

    /**
     * @var TCPDFBarcode
     */
    protected $object;

    /**
     * Sets up the fixture, for example, opens a network connection.
     * This method is called before a test is executed.
     */
    protected function setUp() {
        $this->object = new TCPDFBarcode;
    }

    /**
     * Tears down the fixture, for example, closes a network connection.
     * This method is called after a test is executed.
     */
    protected function tearDown() {
        
    }

    /**
     * @covers TCPDFBarcode::getBarcodeArray
     * @todo   Implement testGetBarcodeArray().
     */
    public function testGetBarcodeArray() {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
                'This test has not been implemented yet.'
        );
    }

    /**
     * @covers TCPDFBarcode::getBarcodeSVG
     * @todo   Implement testGetBarcodeSVG().
     */
    public function testGetBarcodeSVG() {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
                'This test has not been implemented yet.'
        );
    }

    /**
     * @covers TCPDFBarcode::getBarcodeSVGcode
     * @todo   Implement testGetBarcodeSVGcode().
     */
    public function testGetBarcodeSVGcode() {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
                'This test has not been implemented yet.'
        );
    }

    /**
     * @covers TCPDFBarcode::getBarcodeHTML
     * @todo   Implement testGetBarcodeHTML().
     */
    public function testGetBarcodeHTML() {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
                'This test has not been implemented yet.'
        );
    }

    /**
     * @covers TCPDFBarcode::getBarcodePNG
     * @todo   Implement testGetBarcodePNG().
     */
    public function testGetBarcodePNG() {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
                'This test has not been implemented yet.'
        );
    }

    /**
     * @covers TCPDFBarcode::setBarcode
     * @todo   Implement testSetBarcode().
     */
    public function testSetBarcode() {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
                'This test has not been implemented yet.'
        );
    }

    /**
     * @covers TCPDFBarcode::dec_to_hex
     * @todo   Implement testDec_to_hex().
     */
    public function testDec_to_hex() {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
                'This test has not been implemented yet.'
        );
    }

    /**
     * @covers TCPDFBarcode::hex_to_dec
     * @todo   Implement testHex_to_dec().
     */
    public function testHex_to_dec() {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
                'This test has not been implemented yet.'
        );
    }

}
