<?php

/**
 * Generated by PHPUnit_SkeletonGenerator 1.2.1 on 2014-08-09 at 08:18:04.
 */
class TCPDF_ENCODING_MAPSTest extends PHPUnit_Framework_TestCase {

    /**
     * @var TCPDF_ENCODING_MAPS
     */
    protected $object;

    /**
     * Sets up the fixture, for example, opens a network connection.
     * This method is called before a test is executed.
     */
    protected function setUp() {
        $this->object = new TCPDF_ENCODING_MAPS;
    }

    /**
     * Tears down the fixture, for example, closes a network connection.
     * This method is called after a test is executed.
     */
    protected function tearDown() {
        
    }

}
