<?php

/**
 * Generated by PHPUnit_SkeletonGenerator 1.2.1 on 2014-08-09 at 08:17:57.
 */
class TCPDFTest extends PHPUnit_Framework_TestCase {

    /**
     * @var TCPDF
     */
    protected $object;

    /**
     * Sets up the fixture, for example, opens a network connection.
     * This method is called before a test is executed.
     */
    protected function setUp() {
        $this->object = new TCPDF;
    }

    /**
     * Tears down the fixture, for example, closes a network connection.
     * This method is called after a test is executed.
     */
    protected function tearDown() {
        
    }

    /**
     * @covers TCPDF::__destruct
     * @todo   Implement test__destruct().
     */
    public function test__destruct() {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
                'This test has not been implemented yet.'
        );
    }

    /**
     * @covers TCPDF::getTCPDFVersion
     * @todo   Implement testGetTCPDFVersion().
     */
    public function testGetTCPDFVersion() {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
                'This test has not been implemented yet.'
        );
    }

    /**
     * @covers TCPDF::setPageUnit
     * @todo   Implement testSetPageUnit().
     */
    public function testSetPageUnit() {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
                'This test has not been implemented yet.'
        );
    }

    /**
     * @covers TCPDF::getPageSizeFromFormat
     * @todo   Implement testGetPageSizeFromFormat().
     */
    public function testGetPageSizeFromFormat() {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
                'This test has not been implemented yet.'
        );
    }

    /**
     * @covers TCPDF::setPageBoxes
     * @todo   Implement testSetPageBoxes().
     */
    public function testSetPageBoxes() {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
                'This test has not been implemented yet.'
        );
    }

    /**
     * @covers TCPDF::setPageOrientation
     * @todo   Implement testSetPageOrientation().
     */
    public function testSetPageOrientation() {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
                'This test has not been implemented yet.'
        );
    }

    /**
     * @covers TCPDF::setSpacesRE
     * @todo   Implement testSetSpacesRE().
     */
    public function testSetSpacesRE() {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
                'This test has not been implemented yet.'
        );
    }

    /**
     * @covers TCPDF::setRTL
     * @todo   Implement testSetRTL().
     */
    public function testSetRTL() {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
                'This test has not been implemented yet.'
        );
    }

    /**
     * @covers TCPDF::getRTL
     * @todo   Implement testGetRTL().
     */
    public function testGetRTL() {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
                'This test has not been implemented yet.'
        );
    }

    /**
     * @covers TCPDF::setTempRTL
     * @todo   Implement testSetTempRTL().
     */
    public function testSetTempRTL() {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
                'This test has not been implemented yet.'
        );
    }

    /**
     * @covers TCPDF::isRTLTextDir
     * @todo   Implement testIsRTLTextDir().
     */
    public function testIsRTLTextDir() {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
                'This test has not been implemented yet.'
        );
    }

    /**
     * @covers TCPDF::setLastH
     * @todo   Implement testSetLastH().
     */
    public function testSetLastH() {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
                'This test has not been implemented yet.'
        );
    }

    /**
     * @covers TCPDF::resetLastH
     * @todo   Implement testResetLastH().
     */
    public function testResetLastH() {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
                'This test has not been implemented yet.'
        );
    }

    /**
     * @covers TCPDF::getLastH
     * @todo   Implement testGetLastH().
     */
    public function testGetLastH() {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
                'This test has not been implemented yet.'
        );
    }

    /**
     * @covers TCPDF::setImageScale
     * @todo   Implement testSetImageScale().
     */
    public function testSetImageScale() {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
                'This test has not been implemented yet.'
        );
    }

    /**
     * @covers TCPDF::getImageScale
     * @todo   Implement testGetImageScale().
     */
    public function testGetImageScale() {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
                'This test has not been implemented yet.'
        );
    }

    /**
     * @covers TCPDF::getPageDimensions
     * @todo   Implement testGetPageDimensions().
     */
    public function testGetPageDimensions() {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
                'This test has not been implemented yet.'
        );
    }

    /**
     * @covers TCPDF::getPageWidth
     * @todo   Implement testGetPageWidth().
     */
    public function testGetPageWidth() {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
                'This test has not been implemented yet.'
        );
    }

    /**
     * @covers TCPDF::getPageHeight
     * @todo   Implement testGetPageHeight().
     */
    public function testGetPageHeight() {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
                'This test has not been implemented yet.'
        );
    }

    /**
     * @covers TCPDF::getBreakMargin
     * @todo   Implement testGetBreakMargin().
     */
    public function testGetBreakMargin() {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
                'This test has not been implemented yet.'
        );
    }

    /**
     * @covers TCPDF::getScaleFactor
     * @todo   Implement testGetScaleFactor().
     */
    public function testGetScaleFactor() {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
                'This test has not been implemented yet.'
        );
    }

    /**
     * @covers TCPDF::SetMargins
     * @todo   Implement testSetMargins().
     */
    public function testSetMargins() {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
                'This test has not been implemented yet.'
        );
    }

    /**
     * @covers TCPDF::SetLeftMargin
     * @todo   Implement testSetLeftMargin().
     */
    public function testSetLeftMargin() {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
                'This test has not been implemented yet.'
        );
    }

    /**
     * @covers TCPDF::SetTopMargin
     * @todo   Implement testSetTopMargin().
     */
    public function testSetTopMargin() {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
                'This test has not been implemented yet.'
        );
    }

    /**
     * @covers TCPDF::SetRightMargin
     * @todo   Implement testSetRightMargin().
     */
    public function testSetRightMargin() {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
                'This test has not been implemented yet.'
        );
    }

    /**
     * @covers TCPDF::SetCellPadding
     * @todo   Implement testSetCellPadding().
     */
    public function testSetCellPadding() {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
                'This test has not been implemented yet.'
        );
    }

    /**
     * @covers TCPDF::setCellPaddings
     * @todo   Implement testSetCellPaddings().
     */
    public function testSetCellPaddings() {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
                'This test has not been implemented yet.'
        );
    }

    /**
     * @covers TCPDF::getCellPaddings
     * @todo   Implement testGetCellPaddings().
     */
    public function testGetCellPaddings() {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
                'This test has not been implemented yet.'
        );
    }

    /**
     * @covers TCPDF::setCellMargins
     * @todo   Implement testSetCellMargins().
     */
    public function testSetCellMargins() {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
                'This test has not been implemented yet.'
        );
    }

    /**
     * @covers TCPDF::getCellMargins
     * @todo   Implement testGetCellMargins().
     */
    public function testGetCellMargins() {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
                'This test has not been implemented yet.'
        );
    }

    /**
     * @covers TCPDF::SetAutoPageBreak
     * @todo   Implement testSetAutoPageBreak().
     */
    public function testSetAutoPageBreak() {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
                'This test has not been implemented yet.'
        );
    }

    /**
     * @covers TCPDF::getAutoPageBreak
     * @todo   Implement testGetAutoPageBreak().
     */
    public function testGetAutoPageBreak() {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
                'This test has not been implemented yet.'
        );
    }

    /**
     * @covers TCPDF::SetDisplayMode
     * @todo   Implement testSetDisplayMode().
     */
    public function testSetDisplayMode() {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
                'This test has not been implemented yet.'
        );
    }

    /**
     * @covers TCPDF::SetCompression
     * @todo   Implement testSetCompression().
     */
    public function testSetCompression() {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
                'This test has not been implemented yet.'
        );
    }

    /**
     * @covers TCPDF::setSRGBmode
     * @todo   Implement testSetSRGBmode().
     */
    public function testSetSRGBmode() {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
                'This test has not been implemented yet.'
        );
    }

    /**
     * @covers TCPDF::SetDocInfoUnicode
     * @todo   Implement testSetDocInfoUnicode().
     */
    public function testSetDocInfoUnicode() {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
                'This test has not been implemented yet.'
        );
    }

    /**
     * @covers TCPDF::SetTitle
     * @todo   Implement testSetTitle().
     */
    public function testSetTitle() {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
                'This test has not been implemented yet.'
        );
    }

    /**
     * @covers TCPDF::SetSubject
     * @todo   Implement testSetSubject().
     */
    public function testSetSubject() {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
                'This test has not been implemented yet.'
        );
    }

    /**
     * @covers TCPDF::SetAuthor
     * @todo   Implement testSetAuthor().
     */
    public function testSetAuthor() {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
                'This test has not been implemented yet.'
        );
    }

    /**
     * @covers TCPDF::SetKeywords
     * @todo   Implement testSetKeywords().
     */
    public function testSetKeywords() {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
                'This test has not been implemented yet.'
        );
    }

    /**
     * @covers TCPDF::SetCreator
     * @todo   Implement testSetCreator().
     */
    public function testSetCreator() {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
                'This test has not been implemented yet.'
        );
    }

    /**
     * @covers TCPDF::Error
     * @todo   Implement testError().
     */
    public function testError() {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
                'This test has not been implemented yet.'
        );
    }

    /**
     * @covers TCPDF::Open
     * @todo   Implement testOpen().
     */
    public function testOpen() {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
                'This test has not been implemented yet.'
        );
    }

    /**
     * @covers TCPDF::Close
     * @todo   Implement testClose().
     */
    public function testClose() {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
                'This test has not been implemented yet.'
        );
    }

    /**
     * @covers TCPDF::setPage
     * @todo   Implement testSetPage().
     */
    public function testSetPage() {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
                'This test has not been implemented yet.'
        );
    }

    /**
     * @covers TCPDF::lastPage
     * @todo   Implement testLastPage().
     */
    public function testLastPage() {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
                'This test has not been implemented yet.'
        );
    }

    /**
     * @covers TCPDF::getPage
     * @todo   Implement testGetPage().
     */
    public function testGetPage() {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
                'This test has not been implemented yet.'
        );
    }

    /**
     * @covers TCPDF::getNumPages
     * @todo   Implement testGetNumPages().
     */
    public function testGetNumPages() {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
                'This test has not been implemented yet.'
        );
    }

    /**
     * @covers TCPDF::addTOCPage
     * @todo   Implement testAddTOCPage().
     */
    public function testAddTOCPage() {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
                'This test has not been implemented yet.'
        );
    }

    /**
     * @covers TCPDF::endTOCPage
     * @todo   Implement testEndTOCPage().
     */
    public function testEndTOCPage() {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
                'This test has not been implemented yet.'
        );
    }

    /**
     * @covers TCPDF::AddPage
     * @todo   Implement testAddPage().
     */
    public function testAddPage() {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
                'This test has not been implemented yet.'
        );
    }

    /**
     * @covers TCPDF::endPage
     * @todo   Implement testEndPage().
     */
    public function testEndPage() {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
                'This test has not been implemented yet.'
        );
    }

    /**
     * @covers TCPDF::startPage
     * @todo   Implement testStartPage().
     */
    public function testStartPage() {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
                'This test has not been implemented yet.'
        );
    }

    /**
     * @covers TCPDF::setPageMark
     * @todo   Implement testSetPageMark().
     */
    public function testSetPageMark() {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
                'This test has not been implemented yet.'
        );
    }

    /**
     * @covers TCPDF::setHeaderData
     * @todo   Implement testSetHeaderData().
     */
    public function testSetHeaderData() {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
                'This test has not been implemented yet.'
        );
    }

    /**
     * @covers TCPDF::getHeaderData
     * @todo   Implement testGetHeaderData().
     */
    public function testGetHeaderData() {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
                'This test has not been implemented yet.'
        );
    }

    /**
     * @covers TCPDF::setHeaderMargin
     * @todo   Implement testSetHeaderMargin().
     */
    public function testSetHeaderMargin() {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
                'This test has not been implemented yet.'
        );
    }

    /**
     * @covers TCPDF::getHeaderMargin
     * @todo   Implement testGetHeaderMargin().
     */
    public function testGetHeaderMargin() {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
                'This test has not been implemented yet.'
        );
    }

    /**
     * @covers TCPDF::setFooterMargin
     * @todo   Implement testSetFooterMargin().
     */
    public function testSetFooterMargin() {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
                'This test has not been implemented yet.'
        );
    }

    /**
     * @covers TCPDF::getFooterMargin
     * @todo   Implement testGetFooterMargin().
     */
    public function testGetFooterMargin() {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
                'This test has not been implemented yet.'
        );
    }

    /**
     * @covers TCPDF::setPrintHeader
     * @todo   Implement testSetPrintHeader().
     */
    public function testSetPrintHeader() {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
                'This test has not been implemented yet.'
        );
    }

    /**
     * @covers TCPDF::setPrintFooter
     * @todo   Implement testSetPrintFooter().
     */
    public function testSetPrintFooter() {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
                'This test has not been implemented yet.'
        );
    }

    /**
     * @covers TCPDF::getImageRBX
     * @todo   Implement testGetImageRBX().
     */
    public function testGetImageRBX() {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
                'This test has not been implemented yet.'
        );
    }

    /**
     * @covers TCPDF::getImageRBY
     * @todo   Implement testGetImageRBY().
     */
    public function testGetImageRBY() {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
                'This test has not been implemented yet.'
        );
    }

    /**
     * @covers TCPDF::resetHeaderTemplate
     * @todo   Implement testResetHeaderTemplate().
     */
    public function testResetHeaderTemplate() {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
                'This test has not been implemented yet.'
        );
    }

    /**
     * @covers TCPDF::setHeaderTemplateAutoreset
     * @todo   Implement testSetHeaderTemplateAutoreset().
     */
    public function testSetHeaderTemplateAutoreset() {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
                'This test has not been implemented yet.'
        );
    }

    /**
     * @covers TCPDF::Header
     * @todo   Implement testHeader().
     */
    public function testHeader() {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
                'This test has not been implemented yet.'
        );
    }

    /**
     * @covers TCPDF::Footer
     * @todo   Implement testFooter().
     */
    public function testFooter() {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
                'This test has not been implemented yet.'
        );
    }

    /**
     * @covers TCPDF::PageNo
     * @todo   Implement testPageNo().
     */
    public function testPageNo() {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
                'This test has not been implemented yet.'
        );
    }

    /**
     * @covers TCPDF::AddSpotColor
     * @todo   Implement testAddSpotColor().
     */
    public function testAddSpotColor() {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
                'This test has not been implemented yet.'
        );
    }

    /**
     * @covers TCPDF::getSpotColor
     * @todo   Implement testGetSpotColor().
     */
    public function testGetSpotColor() {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
                'This test has not been implemented yet.'
        );
    }

    /**
     * @covers TCPDF::setSpotColor
     * @todo   Implement testSetSpotColor().
     */
    public function testSetSpotColor() {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
                'This test has not been implemented yet.'
        );
    }

    /**
     * @covers TCPDF::SetDrawSpotColor
     * @todo   Implement testSetDrawSpotColor().
     */
    public function testSetDrawSpotColor() {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
                'This test has not been implemented yet.'
        );
    }

    /**
     * @covers TCPDF::SetFillSpotColor
     * @todo   Implement testSetFillSpotColor().
     */
    public function testSetFillSpotColor() {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
                'This test has not been implemented yet.'
        );
    }

    /**
     * @covers TCPDF::SetTextSpotColor
     * @todo   Implement testSetTextSpotColor().
     */
    public function testSetTextSpotColor() {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
                'This test has not been implemented yet.'
        );
    }

    /**
     * @covers TCPDF::setColorArray
     * @todo   Implement testSetColorArray().
     */
    public function testSetColorArray() {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
                'This test has not been implemented yet.'
        );
    }

    /**
     * @covers TCPDF::SetDrawColorArray
     * @todo   Implement testSetDrawColorArray().
     */
    public function testSetDrawColorArray() {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
                'This test has not been implemented yet.'
        );
    }

    /**
     * @covers TCPDF::SetFillColorArray
     * @todo   Implement testSetFillColorArray().
     */
    public function testSetFillColorArray() {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
                'This test has not been implemented yet.'
        );
    }

    /**
     * @covers TCPDF::SetTextColorArray
     * @todo   Implement testSetTextColorArray().
     */
    public function testSetTextColorArray() {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
                'This test has not been implemented yet.'
        );
    }

    /**
     * @covers TCPDF::setColor
     * @todo   Implement testSetColor().
     */
    public function testSetColor() {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
                'This test has not been implemented yet.'
        );
    }

    /**
     * @covers TCPDF::SetDrawColor
     * @todo   Implement testSetDrawColor().
     */
    public function testSetDrawColor() {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
                'This test has not been implemented yet.'
        );
    }

    /**
     * @covers TCPDF::SetFillColor
     * @todo   Implement testSetFillColor().
     */
    public function testSetFillColor() {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
                'This test has not been implemented yet.'
        );
    }

    /**
     * @covers TCPDF::SetTextColor
     * @todo   Implement testSetTextColor().
     */
    public function testSetTextColor() {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
                'This test has not been implemented yet.'
        );
    }

    /**
     * @covers TCPDF::GetStringWidth
     * @todo   Implement testGetStringWidth().
     */
    public function testGetStringWidth() {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
                'This test has not been implemented yet.'
        );
    }

    /**
     * @covers TCPDF::GetArrStringWidth
     * @todo   Implement testGetArrStringWidth().
     */
    public function testGetArrStringWidth() {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
                'This test has not been implemented yet.'
        );
    }

    /**
     * @covers TCPDF::GetCharWidth
     * @todo   Implement testGetCharWidth().
     */
    public function testGetCharWidth() {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
                'This test has not been implemented yet.'
        );
    }

    /**
     * @covers TCPDF::getRawCharWidth
     * @todo   Implement testGetRawCharWidth().
     */
    public function testGetRawCharWidth() {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
                'This test has not been implemented yet.'
        );
    }

    /**
     * @covers TCPDF::GetNumChars
     * @todo   Implement testGetNumChars().
     */
    public function testGetNumChars() {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
                'This test has not been implemented yet.'
        );
    }

    /**
     * @covers TCPDF::AddFont
     * @todo   Implement testAddFont().
     */
    public function testAddFont() {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
                'This test has not been implemented yet.'
        );
    }

    /**
     * @covers TCPDF::SetFont
     * @todo   Implement testSetFont().
     */
    public function testSetFont() {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
                'This test has not been implemented yet.'
        );
    }

    /**
     * @covers TCPDF::SetFontSize
     * @todo   Implement testSetFontSize().
     */
    public function testSetFontSize() {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
                'This test has not been implemented yet.'
        );
    }

    /**
     * @covers TCPDF::getFontBBox
     * @todo   Implement testGetFontBBox().
     */
    public function testGetFontBBox() {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
                'This test has not been implemented yet.'
        );
    }

    /**
     * @covers TCPDF::getFontDescent
     * @todo   Implement testGetFontDescent().
     */
    public function testGetFontDescent() {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
                'This test has not been implemented yet.'
        );
    }

    /**
     * @covers TCPDF::getFontAscent
     * @todo   Implement testGetFontAscent().
     */
    public function testGetFontAscent() {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
                'This test has not been implemented yet.'
        );
    }

    /**
     * @covers TCPDF::isCharDefined
     * @todo   Implement testIsCharDefined().
     */
    public function testIsCharDefined() {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
                'This test has not been implemented yet.'
        );
    }

    /**
     * @covers TCPDF::replaceMissingChars
     * @todo   Implement testReplaceMissingChars().
     */
    public function testReplaceMissingChars() {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
                'This test has not been implemented yet.'
        );
    }

    /**
     * @covers TCPDF::SetDefaultMonospacedFont
     * @todo   Implement testSetDefaultMonospacedFont().
     */
    public function testSetDefaultMonospacedFont() {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
                'This test has not been implemented yet.'
        );
    }

    /**
     * @covers TCPDF::AddLink
     * @todo   Implement testAddLink().
     */
    public function testAddLink() {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
                'This test has not been implemented yet.'
        );
    }

    /**
     * @covers TCPDF::SetLink
     * @todo   Implement testSetLink().
     */
    public function testSetLink() {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
                'This test has not been implemented yet.'
        );
    }

    /**
     * @covers TCPDF::Link
     * @todo   Implement testLink().
     */
    public function testLink() {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
                'This test has not been implemented yet.'
        );
    }

    /**
     * @covers TCPDF::Annotation
     * @todo   Implement testAnnotation().
     */
    public function testAnnotation() {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
                'This test has not been implemented yet.'
        );
    }

    /**
     * @covers TCPDF::Text
     * @todo   Implement testText().
     */
    public function testText() {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
                'This test has not been implemented yet.'
        );
    }

    /**
     * @covers TCPDF::AcceptPageBreak
     * @todo   Implement testAcceptPageBreak().
     */
    public function testAcceptPageBreak() {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
                'This test has not been implemented yet.'
        );
    }

    /**
     * @covers TCPDF::checkPageBreak
     * @todo   Implement testCheckPageBreak().
     */
    public function testCheckPageBreak() {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
                'This test has not been implemented yet.'
        );
    }

    /**
     * @covers TCPDF::removeSHY
     * @todo   Implement testRemoveSHY().
     */
    public function testRemoveSHY() {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
                'This test has not been implemented yet.'
        );
    }

    /**
     * @covers TCPDF::Cell
     * @todo   Implement testCell().
     */
    public function testCell() {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
                'This test has not been implemented yet.'
        );
    }

    /**
     * @covers TCPDF::MultiCell
     * @todo   Implement testMultiCell().
     */
    public function testMultiCell() {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
                'This test has not been implemented yet.'
        );
    }

    /**
     * @covers TCPDF::getNumLines
     * @todo   Implement testGetNumLines().
     */
    public function testGetNumLines() {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
                'This test has not been implemented yet.'
        );
    }

    /**
     * @covers TCPDF::getStringHeight
     * @todo   Implement testGetStringHeight().
     */
    public function testGetStringHeight() {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
                'This test has not been implemented yet.'
        );
    }

    /**
     * @covers TCPDF::Write
     * @todo   Implement testWrite().
     */
    public function testWrite() {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
                'This test has not been implemented yet.'
        );
    }

    /**
     * @covers TCPDF::UTF8ArrSubString
     * @todo   Implement testUTF8ArrSubString().
     */
    public function testUTF8ArrSubString() {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
                'This test has not been implemented yet.'
        );
    }

    /**
     * @covers TCPDF::UniArrSubString
     * @todo   Implement testUniArrSubString().
     */
    public function testUniArrSubString() {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
                'This test has not been implemented yet.'
        );
    }

    /**
     * @covers TCPDF::UTF8ArrayToUniArray
     * @todo   Implement testUTF8ArrayToUniArray().
     */
    public function testUTF8ArrayToUniArray() {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
                'This test has not been implemented yet.'
        );
    }

    /**
     * @covers TCPDF::unichr
     * @todo   Implement testUnichr().
     */
    public function testUnichr() {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
                'This test has not been implemented yet.'
        );
    }

    /**
     * @covers TCPDF::getImageFileType
     * @todo   Implement testGetImageFileType().
     */
    public function testGetImageFileType() {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
                'This test has not been implemented yet.'
        );
    }

    /**
     * @covers TCPDF::Image
     * @todo   Implement testImage().
     */
    public function testImage() {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
                'This test has not been implemented yet.'
        );
    }

    /**
     * @covers TCPDF::set_mqr
     * @todo   Implement testSet_mqr().
     */
    public function testSet_mqr() {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
                'This test has not been implemented yet.'
        );
    }

    /**
     * @covers TCPDF::get_mqr
     * @todo   Implement testGet_mqr().
     */
    public function testGet_mqr() {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
                'This test has not been implemented yet.'
        );
    }

    /**
     * @covers TCPDF::Ln
     * @todo   Implement testLn().
     */
    public function testLn() {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
                'This test has not been implemented yet.'
        );
    }

    /**
     * @covers TCPDF::GetX
     * @todo   Implement testGetX().
     */
    public function testGetX() {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
                'This test has not been implemented yet.'
        );
    }

    /**
     * @covers TCPDF::GetAbsX
     * @todo   Implement testGetAbsX().
     */
    public function testGetAbsX() {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
                'This test has not been implemented yet.'
        );
    }

    /**
     * @covers TCPDF::GetY
     * @todo   Implement testGetY().
     */
    public function testGetY() {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
                'This test has not been implemented yet.'
        );
    }

    /**
     * @covers TCPDF::SetX
     * @todo   Implement testSetX().
     */
    public function testSetX() {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
                'This test has not been implemented yet.'
        );
    }

    /**
     * @covers TCPDF::SetY
     * @todo   Implement testSetY().
     */
    public function testSetY() {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
                'This test has not been implemented yet.'
        );
    }

    /**
     * @covers TCPDF::SetXY
     * @todo   Implement testSetXY().
     */
    public function testSetXY() {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
                'This test has not been implemented yet.'
        );
    }

    /**
     * @covers TCPDF::Output
     * @todo   Implement testOutput().
     */
    public function testOutput() {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
                'This test has not been implemented yet.'
        );
    }

    /**
     * @covers TCPDF::_destroy
     * @todo   Implement test_destroy().
     */
    public function test_destroy() {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
                'This test has not been implemented yet.'
        );
    }

    /**
     * @covers TCPDF::addTTFfont
     * @todo   Implement testAddTTFfont().
     */
    public function testAddTTFfont() {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
                'This test has not been implemented yet.'
        );
    }

    /**
     * @covers TCPDF::setExtraXMP
     * @todo   Implement testSetExtraXMP().
     */
    public function testSetExtraXMP() {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
                'This test has not been implemented yet.'
        );
    }

    /**
     * @covers TCPDF::setDocCreationTimestamp
     * @todo   Implement testSetDocCreationTimestamp().
     */
    public function testSetDocCreationTimestamp() {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
                'This test has not been implemented yet.'
        );
    }

    /**
     * @covers TCPDF::setDocModificationTimestamp
     * @todo   Implement testSetDocModificationTimestamp().
     */
    public function testSetDocModificationTimestamp() {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
                'This test has not been implemented yet.'
        );
    }

    /**
     * @covers TCPDF::getDocCreationTimestamp
     * @todo   Implement testGetDocCreationTimestamp().
     */
    public function testGetDocCreationTimestamp() {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
                'This test has not been implemented yet.'
        );
    }

    /**
     * @covers TCPDF::getDocModificationTimestamp
     * @todo   Implement testGetDocModificationTimestamp().
     */
    public function testGetDocModificationTimestamp() {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
                'This test has not been implemented yet.'
        );
    }

    /**
     * @covers TCPDF::getTimestamp
     * @todo   Implement testGetTimestamp().
     */
    public function testGetTimestamp() {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
                'This test has not been implemented yet.'
        );
    }

    /**
     * @covers TCPDF::getFormattedDate
     * @todo   Implement testGetFormattedDate().
     */
    public function testGetFormattedDate() {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
                'This test has not been implemented yet.'
        );
    }

    /**
     * @covers TCPDF::setHeaderFont
     * @todo   Implement testSetHeaderFont().
     */
    public function testSetHeaderFont() {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
                'This test has not been implemented yet.'
        );
    }

    /**
     * @covers TCPDF::getHeaderFont
     * @todo   Implement testGetHeaderFont().
     */
    public function testGetHeaderFont() {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
                'This test has not been implemented yet.'
        );
    }

    /**
     * @covers TCPDF::setFooterFont
     * @todo   Implement testSetFooterFont().
     */
    public function testSetFooterFont() {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
                'This test has not been implemented yet.'
        );
    }

    /**
     * @covers TCPDF::getFooterFont
     * @todo   Implement testGetFooterFont().
     */
    public function testGetFooterFont() {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
                'This test has not been implemented yet.'
        );
    }

    /**
     * @covers TCPDF::setLanguageArray
     * @todo   Implement testSetLanguageArray().
     */
    public function testSetLanguageArray() {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
                'This test has not been implemented yet.'
        );
    }

    /**
     * @covers TCPDF::getPDFData
     * @todo   Implement testGetPDFData().
     */
    public function testGetPDFData() {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
                'This test has not been implemented yet.'
        );
    }

    /**
     * @covers TCPDF::addHtmlLink
     * @todo   Implement testAddHtmlLink().
     */
    public function testAddHtmlLink() {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
                'This test has not been implemented yet.'
        );
    }

    /**
     * @covers TCPDF::convertHTMLColorToDec
     * @todo   Implement testConvertHTMLColorToDec().
     */
    public function testConvertHTMLColorToDec() {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
                'This test has not been implemented yet.'
        );
    }

    /**
     * @covers TCPDF::pixelsToUnits
     * @todo   Implement testPixelsToUnits().
     */
    public function testPixelsToUnits() {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
                'This test has not been implemented yet.'
        );
    }

    /**
     * @covers TCPDF::unhtmlentities
     * @todo   Implement testUnhtmlentities().
     */
    public function testUnhtmlentities() {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
                'This test has not been implemented yet.'
        );
    }

    /**
     * @covers TCPDF::SetProtection
     * @todo   Implement testSetProtection().
     */
    public function testSetProtection() {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
                'This test has not been implemented yet.'
        );
    }

    /**
     * @covers TCPDF::StartTransform
     * @todo   Implement testStartTransform().
     */
    public function testStartTransform() {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
                'This test has not been implemented yet.'
        );
    }

    /**
     * @covers TCPDF::StopTransform
     * @todo   Implement testStopTransform().
     */
    public function testStopTransform() {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
                'This test has not been implemented yet.'
        );
    }

    /**
     * @covers TCPDF::ScaleX
     * @todo   Implement testScaleX().
     */
    public function testScaleX() {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
                'This test has not been implemented yet.'
        );
    }

    /**
     * @covers TCPDF::ScaleY
     * @todo   Implement testScaleY().
     */
    public function testScaleY() {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
                'This test has not been implemented yet.'
        );
    }

    /**
     * @covers TCPDF::ScaleXY
     * @todo   Implement testScaleXY().
     */
    public function testScaleXY() {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
                'This test has not been implemented yet.'
        );
    }

    /**
     * @covers TCPDF::Scale
     * @todo   Implement testScale().
     */
    public function testScale() {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
                'This test has not been implemented yet.'
        );
    }

    /**
     * @covers TCPDF::MirrorH
     * @todo   Implement testMirrorH().
     */
    public function testMirrorH() {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
                'This test has not been implemented yet.'
        );
    }

    /**
     * @covers TCPDF::MirrorV
     * @todo   Implement testMirrorV().
     */
    public function testMirrorV() {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
                'This test has not been implemented yet.'
        );
    }

    /**
     * @covers TCPDF::MirrorP
     * @todo   Implement testMirrorP().
     */
    public function testMirrorP() {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
                'This test has not been implemented yet.'
        );
    }

    /**
     * @covers TCPDF::MirrorL
     * @todo   Implement testMirrorL().
     */
    public function testMirrorL() {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
                'This test has not been implemented yet.'
        );
    }

    /**
     * @covers TCPDF::TranslateX
     * @todo   Implement testTranslateX().
     */
    public function testTranslateX() {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
                'This test has not been implemented yet.'
        );
    }

    /**
     * @covers TCPDF::TranslateY
     * @todo   Implement testTranslateY().
     */
    public function testTranslateY() {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
                'This test has not been implemented yet.'
        );
    }

    /**
     * @covers TCPDF::Translate
     * @todo   Implement testTranslate().
     */
    public function testTranslate() {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
                'This test has not been implemented yet.'
        );
    }

    /**
     * @covers TCPDF::Rotate
     * @todo   Implement testRotate().
     */
    public function testRotate() {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
                'This test has not been implemented yet.'
        );
    }

    /**
     * @covers TCPDF::SkewX
     * @todo   Implement testSkewX().
     */
    public function testSkewX() {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
                'This test has not been implemented yet.'
        );
    }

    /**
     * @covers TCPDF::SkewY
     * @todo   Implement testSkewY().
     */
    public function testSkewY() {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
                'This test has not been implemented yet.'
        );
    }

    /**
     * @covers TCPDF::Skew
     * @todo   Implement testSkew().
     */
    public function testSkew() {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
                'This test has not been implemented yet.'
        );
    }

    /**
     * @covers TCPDF::SetLineWidth
     * @todo   Implement testSetLineWidth().
     */
    public function testSetLineWidth() {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
                'This test has not been implemented yet.'
        );
    }

    /**
     * @covers TCPDF::GetLineWidth
     * @todo   Implement testGetLineWidth().
     */
    public function testGetLineWidth() {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
                'This test has not been implemented yet.'
        );
    }

    /**
     * @covers TCPDF::SetLineStyle
     * @todo   Implement testSetLineStyle().
     */
    public function testSetLineStyle() {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
                'This test has not been implemented yet.'
        );
    }

    /**
     * @covers TCPDF::Line
     * @todo   Implement testLine().
     */
    public function testLine() {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
                'This test has not been implemented yet.'
        );
    }

    /**
     * @covers TCPDF::Rect
     * @todo   Implement testRect().
     */
    public function testRect() {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
                'This test has not been implemented yet.'
        );
    }

    /**
     * @covers TCPDF::Curve
     * @todo   Implement testCurve().
     */
    public function testCurve() {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
                'This test has not been implemented yet.'
        );
    }

    /**
     * @covers TCPDF::Polycurve
     * @todo   Implement testPolycurve().
     */
    public function testPolycurve() {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
                'This test has not been implemented yet.'
        );
    }

    /**
     * @covers TCPDF::Ellipse
     * @todo   Implement testEllipse().
     */
    public function testEllipse() {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
                'This test has not been implemented yet.'
        );
    }

    /**
     * @covers TCPDF::Circle
     * @todo   Implement testCircle().
     */
    public function testCircle() {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
                'This test has not been implemented yet.'
        );
    }

    /**
     * @covers TCPDF::PolyLine
     * @todo   Implement testPolyLine().
     */
    public function testPolyLine() {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
                'This test has not been implemented yet.'
        );
    }

    /**
     * @covers TCPDF::Polygon
     * @todo   Implement testPolygon().
     */
    public function testPolygon() {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
                'This test has not been implemented yet.'
        );
    }

    /**
     * @covers TCPDF::RegularPolygon
     * @todo   Implement testRegularPolygon().
     */
    public function testRegularPolygon() {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
                'This test has not been implemented yet.'
        );
    }

    /**
     * @covers TCPDF::StarPolygon
     * @todo   Implement testStarPolygon().
     */
    public function testStarPolygon() {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
                'This test has not been implemented yet.'
        );
    }

    /**
     * @covers TCPDF::RoundedRect
     * @todo   Implement testRoundedRect().
     */
    public function testRoundedRect() {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
                'This test has not been implemented yet.'
        );
    }

    /**
     * @covers TCPDF::RoundedRectXY
     * @todo   Implement testRoundedRectXY().
     */
    public function testRoundedRectXY() {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
                'This test has not been implemented yet.'
        );
    }

    /**
     * @covers TCPDF::Arrow
     * @todo   Implement testArrow().
     */
    public function testArrow() {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
                'This test has not been implemented yet.'
        );
    }

    /**
     * @covers TCPDF::setDestination
     * @todo   Implement testSetDestination().
     */
    public function testSetDestination() {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
                'This test has not been implemented yet.'
        );
    }

    /**
     * @covers TCPDF::getDestination
     * @todo   Implement testGetDestination().
     */
    public function testGetDestination() {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
                'This test has not been implemented yet.'
        );
    }

    /**
     * @covers TCPDF::setBookmark
     * @todo   Implement testSetBookmark().
     */
    public function testSetBookmark() {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
                'This test has not been implemented yet.'
        );
    }

    /**
     * @covers TCPDF::Bookmark
     * @todo   Implement testBookmark().
     */
    public function testBookmark() {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
                'This test has not been implemented yet.'
        );
    }

    /**
     * @covers TCPDF::IncludeJS
     * @todo   Implement testIncludeJS().
     */
    public function testIncludeJS() {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
                'This test has not been implemented yet.'
        );
    }

    /**
     * @covers TCPDF::addJavascriptObject
     * @todo   Implement testAddJavascriptObject().
     */
    public function testAddJavascriptObject() {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
                'This test has not been implemented yet.'
        );
    }

    /**
     * @covers TCPDF::setFormDefaultProp
     * @todo   Implement testSetFormDefaultProp().
     */
    public function testSetFormDefaultProp() {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
                'This test has not been implemented yet.'
        );
    }

    /**
     * @covers TCPDF::getFormDefaultProp
     * @todo   Implement testGetFormDefaultProp().
     */
    public function testGetFormDefaultProp() {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
                'This test has not been implemented yet.'
        );
    }

    /**
     * @covers TCPDF::TextField
     * @todo   Implement testTextField().
     */
    public function testTextField() {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
                'This test has not been implemented yet.'
        );
    }

    /**
     * @covers TCPDF::RadioButton
     * @todo   Implement testRadioButton().
     */
    public function testRadioButton() {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
                'This test has not been implemented yet.'
        );
    }

    /**
     * @covers TCPDF::ListBox
     * @todo   Implement testListBox().
     */
    public function testListBox() {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
                'This test has not been implemented yet.'
        );
    }

    /**
     * @covers TCPDF::ComboBox
     * @todo   Implement testComboBox().
     */
    public function testComboBox() {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
                'This test has not been implemented yet.'
        );
    }

    /**
     * @covers TCPDF::CheckBox
     * @todo   Implement testCheckBox().
     */
    public function testCheckBox() {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
                'This test has not been implemented yet.'
        );
    }

    /**
     * @covers TCPDF::Button
     * @todo   Implement testButton().
     */
    public function testButton() {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
                'This test has not been implemented yet.'
        );
    }

    /**
     * @covers TCPDF::setUserRights
     * @todo   Implement testSetUserRights().
     */
    public function testSetUserRights() {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
                'This test has not been implemented yet.'
        );
    }

    /**
     * @covers TCPDF::setSignature
     * @todo   Implement testSetSignature().
     */
    public function testSetSignature() {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
                'This test has not been implemented yet.'
        );
    }

    /**
     * @covers TCPDF::setSignatureAppearance
     * @todo   Implement testSetSignatureAppearance().
     */
    public function testSetSignatureAppearance() {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
                'This test has not been implemented yet.'
        );
    }

    /**
     * @covers TCPDF::addEmptySignatureAppearance
     * @todo   Implement testAddEmptySignatureAppearance().
     */
    public function testAddEmptySignatureAppearance() {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
                'This test has not been implemented yet.'
        );
    }

    /**
     * @covers TCPDF::startPageGroup
     * @todo   Implement testStartPageGroup().
     */
    public function testStartPageGroup() {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
                'This test has not been implemented yet.'
        );
    }

    /**
     * @covers TCPDF::AliasNbPages
     * @todo   Implement testAliasNbPages().
     */
    public function testAliasNbPages() {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
                'This test has not been implemented yet.'
        );
    }

    /**
     * @covers TCPDF::AliasNumPage
     * @todo   Implement testAliasNumPage().
     */
    public function testAliasNumPage() {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
                'This test has not been implemented yet.'
        );
    }

    /**
     * @covers TCPDF::setStartingPageNumber
     * @todo   Implement testSetStartingPageNumber().
     */
    public function testSetStartingPageNumber() {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
                'This test has not been implemented yet.'
        );
    }

    /**
     * @covers TCPDF::getAliasRightShift
     * @todo   Implement testGetAliasRightShift().
     */
    public function testGetAliasRightShift() {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
                'This test has not been implemented yet.'
        );
    }

    /**
     * @covers TCPDF::getAliasNbPages
     * @todo   Implement testGetAliasNbPages().
     */
    public function testGetAliasNbPages() {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
                'This test has not been implemented yet.'
        );
    }

    /**
     * @covers TCPDF::getAliasNumPage
     * @todo   Implement testGetAliasNumPage().
     */
    public function testGetAliasNumPage() {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
                'This test has not been implemented yet.'
        );
    }

    /**
     * @covers TCPDF::getPageGroupAlias
     * @todo   Implement testGetPageGroupAlias().
     */
    public function testGetPageGroupAlias() {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
                'This test has not been implemented yet.'
        );
    }

    /**
     * @covers TCPDF::getPageNumGroupAlias
     * @todo   Implement testGetPageNumGroupAlias().
     */
    public function testGetPageNumGroupAlias() {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
                'This test has not been implemented yet.'
        );
    }

    /**
     * @covers TCPDF::getGroupPageNo
     * @todo   Implement testGetGroupPageNo().
     */
    public function testGetGroupPageNo() {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
                'This test has not been implemented yet.'
        );
    }

    /**
     * @covers TCPDF::getGroupPageNoFormatted
     * @todo   Implement testGetGroupPageNoFormatted().
     */
    public function testGetGroupPageNoFormatted() {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
                'This test has not been implemented yet.'
        );
    }

    /**
     * @covers TCPDF::PageNoFormatted
     * @todo   Implement testPageNoFormatted().
     */
    public function testPageNoFormatted() {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
                'This test has not been implemented yet.'
        );
    }

    /**
     * @covers TCPDF::startLayer
     * @todo   Implement testStartLayer().
     */
    public function testStartLayer() {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
                'This test has not been implemented yet.'
        );
    }

    /**
     * @covers TCPDF::endLayer
     * @todo   Implement testEndLayer().
     */
    public function testEndLayer() {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
                'This test has not been implemented yet.'
        );
    }

    /**
     * @covers TCPDF::setVisibility
     * @todo   Implement testSetVisibility().
     */
    public function testSetVisibility() {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
                'This test has not been implemented yet.'
        );
    }

    /**
     * @covers TCPDF::setOverprint
     * @todo   Implement testSetOverprint().
     */
    public function testSetOverprint() {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
                'This test has not been implemented yet.'
        );
    }

    /**
     * @covers TCPDF::getOverprint
     * @todo   Implement testGetOverprint().
     */
    public function testGetOverprint() {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
                'This test has not been implemented yet.'
        );
    }

    /**
     * @covers TCPDF::setAlpha
     * @todo   Implement testSetAlpha().
     */
    public function testSetAlpha() {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
                'This test has not been implemented yet.'
        );
    }

    /**
     * @covers TCPDF::getAlpha
     * @todo   Implement testGetAlpha().
     */
    public function testGetAlpha() {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
                'This test has not been implemented yet.'
        );
    }

    /**
     * @covers TCPDF::setJPEGQuality
     * @todo   Implement testSetJPEGQuality().
     */
    public function testSetJPEGQuality() {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
                'This test has not been implemented yet.'
        );
    }

    /**
     * @covers TCPDF::setDefaultTableColumns
     * @todo   Implement testSetDefaultTableColumns().
     */
    public function testSetDefaultTableColumns() {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
                'This test has not been implemented yet.'
        );
    }

    /**
     * @covers TCPDF::setCellHeightRatio
     * @todo   Implement testSetCellHeightRatio().
     */
    public function testSetCellHeightRatio() {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
                'This test has not been implemented yet.'
        );
    }

    /**
     * @covers TCPDF::getCellHeightRatio
     * @todo   Implement testGetCellHeightRatio().
     */
    public function testGetCellHeightRatio() {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
                'This test has not been implemented yet.'
        );
    }

    /**
     * @covers TCPDF::setPDFVersion
     * @todo   Implement testSetPDFVersion().
     */
    public function testSetPDFVersion() {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
                'This test has not been implemented yet.'
        );
    }

    /**
     * @covers TCPDF::setViewerPreferences
     * @todo   Implement testSetViewerPreferences().
     */
    public function testSetViewerPreferences() {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
                'This test has not been implemented yet.'
        );
    }

    /**
     * @covers TCPDF::colorRegistrationBar
     * @todo   Implement testColorRegistrationBar().
     */
    public function testColorRegistrationBar() {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
                'This test has not been implemented yet.'
        );
    }

    /**
     * @covers TCPDF::cropMark
     * @todo   Implement testCropMark().
     */
    public function testCropMark() {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
                'This test has not been implemented yet.'
        );
    }

    /**
     * @covers TCPDF::registrationMark
     * @todo   Implement testRegistrationMark().
     */
    public function testRegistrationMark() {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
                'This test has not been implemented yet.'
        );
    }

    /**
     * @covers TCPDF::LinearGradient
     * @todo   Implement testLinearGradient().
     */
    public function testLinearGradient() {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
                'This test has not been implemented yet.'
        );
    }

    /**
     * @covers TCPDF::RadialGradient
     * @todo   Implement testRadialGradient().
     */
    public function testRadialGradient() {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
                'This test has not been implemented yet.'
        );
    }

    /**
     * @covers TCPDF::CoonsPatchMesh
     * @todo   Implement testCoonsPatchMesh().
     */
    public function testCoonsPatchMesh() {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
                'This test has not been implemented yet.'
        );
    }

    /**
     * @covers TCPDF::Gradient
     * @todo   Implement testGradient().
     */
    public function testGradient() {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
                'This test has not been implemented yet.'
        );
    }

    /**
     * @covers TCPDF::_putshaders
     * @todo   Implement test_putshaders().
     */
    public function test_putshaders() {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
                'This test has not been implemented yet.'
        );
    }

    /**
     * @covers TCPDF::PieSector
     * @todo   Implement testPieSector().
     */
    public function testPieSector() {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
                'This test has not been implemented yet.'
        );
    }

    /**
     * @covers TCPDF::PieSectorXY
     * @todo   Implement testPieSectorXY().
     */
    public function testPieSectorXY() {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
                'This test has not been implemented yet.'
        );
    }

    /**
     * @covers TCPDF::ImageEps
     * @todo   Implement testImageEps().
     */
    public function testImageEps() {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
                'This test has not been implemented yet.'
        );
    }

    /**
     * @covers TCPDF::setBarcode
     * @todo   Implement testSetBarcode().
     */
    public function testSetBarcode() {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
                'This test has not been implemented yet.'
        );
    }

    /**
     * @covers TCPDF::getBarcode
     * @todo   Implement testGetBarcode().
     */
    public function testGetBarcode() {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
                'This test has not been implemented yet.'
        );
    }

    /**
     * @covers TCPDF::write1DBarcode
     * @todo   Implement testWrite1DBarcode().
     */
    public function testWrite1DBarcode() {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
                'This test has not been implemented yet.'
        );
    }

    /**
     * @covers TCPDF::writeBarcode
     * @todo   Implement testWriteBarcode().
     */
    public function testWriteBarcode() {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
                'This test has not been implemented yet.'
        );
    }

    /**
     * @covers TCPDF::write2DBarcode
     * @todo   Implement testWrite2DBarcode().
     */
    public function testWrite2DBarcode() {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
                'This test has not been implemented yet.'
        );
    }

    /**
     * @covers TCPDF::getMargins
     * @todo   Implement testGetMargins().
     */
    public function testGetMargins() {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
                'This test has not been implemented yet.'
        );
    }

    /**
     * @covers TCPDF::getOriginalMargins
     * @todo   Implement testGetOriginalMargins().
     */
    public function testGetOriginalMargins() {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
                'This test has not been implemented yet.'
        );
    }

    /**
     * @covers TCPDF::getFontSize
     * @todo   Implement testGetFontSize().
     */
    public function testGetFontSize() {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
                'This test has not been implemented yet.'
        );
    }

    /**
     * @covers TCPDF::getFontSizePt
     * @todo   Implement testGetFontSizePt().
     */
    public function testGetFontSizePt() {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
                'This test has not been implemented yet.'
        );
    }

    /**
     * @covers TCPDF::getFontFamily
     * @todo   Implement testGetFontFamily().
     */
    public function testGetFontFamily() {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
                'This test has not been implemented yet.'
        );
    }

    /**
     * @covers TCPDF::getFontStyle
     * @todo   Implement testGetFontStyle().
     */
    public function testGetFontStyle() {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
                'This test has not been implemented yet.'
        );
    }

    /**
     * @covers TCPDF::fixHTMLCode
     * @todo   Implement testFixHTMLCode().
     */
    public function testFixHTMLCode() {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
                'This test has not been implemented yet.'
        );
    }

    /**
     * @covers TCPDF::getCSSPadding
     * @todo   Implement testGetCSSPadding().
     */
    public function testGetCSSPadding() {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
                'This test has not been implemented yet.'
        );
    }

    /**
     * @covers TCPDF::getCSSMargin
     * @todo   Implement testGetCSSMargin().
     */
    public function testGetCSSMargin() {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
                'This test has not been implemented yet.'
        );
    }

    /**
     * @covers TCPDF::getCSSBorderMargin
     * @todo   Implement testGetCSSBorderMargin().
     */
    public function testGetCSSBorderMargin() {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
                'This test has not been implemented yet.'
        );
    }

    /**
     * @covers TCPDF::writeHTMLCell
     * @todo   Implement testWriteHTMLCell().
     */
    public function testWriteHTMLCell() {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
                'This test has not been implemented yet.'
        );
    }

    /**
     * @covers TCPDF::writeHTML
     * @todo   Implement testWriteHTML().
     */
    public function testWriteHTML() {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
                'This test has not been implemented yet.'
        );
    }

    /**
     * @covers TCPDF::setLIsymbol
     * @todo   Implement testSetLIsymbol().
     */
    public function testSetLIsymbol() {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
                'This test has not been implemented yet.'
        );
    }

    /**
     * @covers TCPDF::SetBooklet
     * @todo   Implement testSetBooklet().
     */
    public function testSetBooklet() {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
                'This test has not been implemented yet.'
        );
    }

    /**
     * @covers TCPDF::setHtmlVSpace
     * @todo   Implement testSetHtmlVSpace().
     */
    public function testSetHtmlVSpace() {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
                'This test has not been implemented yet.'
        );
    }

    /**
     * @covers TCPDF::setListIndentWidth
     * @todo   Implement testSetListIndentWidth().
     */
    public function testSetListIndentWidth() {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
                'This test has not been implemented yet.'
        );
    }

    /**
     * @covers TCPDF::setOpenCell
     * @todo   Implement testSetOpenCell().
     */
    public function testSetOpenCell() {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
                'This test has not been implemented yet.'
        );
    }

    /**
     * @covers TCPDF::setHtmlLinksStyle
     * @todo   Implement testSetHtmlLinksStyle().
     */
    public function testSetHtmlLinksStyle() {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
                'This test has not been implemented yet.'
        );
    }

    /**
     * @covers TCPDF::getHTMLUnitToUnits
     * @todo   Implement testGetHTMLUnitToUnits().
     */
    public function testGetHTMLUnitToUnits() {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
                'This test has not been implemented yet.'
        );
    }

    /**
     * @covers TCPDF::intToRoman
     * @todo   Implement testIntToRoman().
     */
    public function testIntToRoman() {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
                'This test has not been implemented yet.'
        );
    }

    /**
     * @covers TCPDF::movePage
     * @todo   Implement testMovePage().
     */
    public function testMovePage() {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
                'This test has not been implemented yet.'
        );
    }

    /**
     * @covers TCPDF::deletePage
     * @todo   Implement testDeletePage().
     */
    public function testDeletePage() {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
                'This test has not been implemented yet.'
        );
    }

    /**
     * @covers TCPDF::copyPage
     * @todo   Implement testCopyPage().
     */
    public function testCopyPage() {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
                'This test has not been implemented yet.'
        );
    }

    /**
     * @covers TCPDF::addTOC
     * @todo   Implement testAddTOC().
     */
    public function testAddTOC() {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
                'This test has not been implemented yet.'
        );
    }

    /**
     * @covers TCPDF::addHTMLTOC
     * @todo   Implement testAddHTMLTOC().
     */
    public function testAddHTMLTOC() {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
                'This test has not been implemented yet.'
        );
    }

    /**
     * @covers TCPDF::startTransaction
     * @todo   Implement testStartTransaction().
     */
    public function testStartTransaction() {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
                'This test has not been implemented yet.'
        );
    }

    /**
     * @covers TCPDF::commitTransaction
     * @todo   Implement testCommitTransaction().
     */
    public function testCommitTransaction() {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
                'This test has not been implemented yet.'
        );
    }

    /**
     * @covers TCPDF::rollbackTransaction
     * @todo   Implement testRollbackTransaction().
     */
    public function testRollbackTransaction() {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
                'This test has not been implemented yet.'
        );
    }

    /**
     * @covers TCPDF::objclone
     * @todo   Implement testObjclone().
     */
    public function testObjclone() {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
                'This test has not been implemented yet.'
        );
    }

    /**
     * @covers TCPDF::empty_string
     * @todo   Implement testEmpty_string().
     */
    public function testEmpty_string() {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
                'This test has not been implemented yet.'
        );
    }

    /**
     * @covers TCPDF::revstrpos
     * @todo   Implement testRevstrpos().
     */
    public function testRevstrpos() {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
                'This test has not been implemented yet.'
        );
    }

    /**
     * @covers TCPDF::setEqualColumns
     * @todo   Implement testSetEqualColumns().
     */
    public function testSetEqualColumns() {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
                'This test has not been implemented yet.'
        );
    }

    /**
     * @covers TCPDF::resetColumns
     * @todo   Implement testResetColumns().
     */
    public function testResetColumns() {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
                'This test has not been implemented yet.'
        );
    }

    /**
     * @covers TCPDF::setColumnsArray
     * @todo   Implement testSetColumnsArray().
     */
    public function testSetColumnsArray() {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
                'This test has not been implemented yet.'
        );
    }

    /**
     * @covers TCPDF::selectColumn
     * @todo   Implement testSelectColumn().
     */
    public function testSelectColumn() {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
                'This test has not been implemented yet.'
        );
    }

    /**
     * @covers TCPDF::getColumn
     * @todo   Implement testGetColumn().
     */
    public function testGetColumn() {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
                'This test has not been implemented yet.'
        );
    }

    /**
     * @covers TCPDF::getNumberOfColumns
     * @todo   Implement testGetNumberOfColumns().
     */
    public function testGetNumberOfColumns() {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
                'This test has not been implemented yet.'
        );
    }

    /**
     * @covers TCPDF::serializeTCPDFtagParameters
     * @todo   Implement testSerializeTCPDFtagParameters().
     */
    public function testSerializeTCPDFtagParameters() {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
                'This test has not been implemented yet.'
        );
    }

    /**
     * @covers TCPDF::setTextRenderingMode
     * @todo   Implement testSetTextRenderingMode().
     */
    public function testSetTextRenderingMode() {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
                'This test has not been implemented yet.'
        );
    }

    /**
     * @covers TCPDF::getHyphenPatternsFromTEX
     * @todo   Implement testGetHyphenPatternsFromTEX().
     */
    public function testGetHyphenPatternsFromTEX() {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
                'This test has not been implemented yet.'
        );
    }

    /**
     * @covers TCPDF::hyphenateText
     * @todo   Implement testHyphenateText().
     */
    public function testHyphenateText() {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
                'This test has not been implemented yet.'
        );
    }

    /**
     * @covers TCPDF::setRasterizeVectorImages
     * @todo   Implement testSetRasterizeVectorImages().
     */
    public function testSetRasterizeVectorImages() {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
                'This test has not been implemented yet.'
        );
    }

    /**
     * @covers TCPDF::setFontSubsetting
     * @todo   Implement testSetFontSubsetting().
     */
    public function testSetFontSubsetting() {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
                'This test has not been implemented yet.'
        );
    }

    /**
     * @covers TCPDF::getFontSubsetting
     * @todo   Implement testGetFontSubsetting().
     */
    public function testGetFontSubsetting() {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
                'This test has not been implemented yet.'
        );
    }

    /**
     * @covers TCPDF::stringLeftTrim
     * @todo   Implement testStringLeftTrim().
     */
    public function testStringLeftTrim() {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
                'This test has not been implemented yet.'
        );
    }

    /**
     * @covers TCPDF::stringRightTrim
     * @todo   Implement testStringRightTrim().
     */
    public function testStringRightTrim() {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
                'This test has not been implemented yet.'
        );
    }

    /**
     * @covers TCPDF::stringTrim
     * @todo   Implement testStringTrim().
     */
    public function testStringTrim() {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
                'This test has not been implemented yet.'
        );
    }

    /**
     * @covers TCPDF::isUnicodeFont
     * @todo   Implement testIsUnicodeFont().
     */
    public function testIsUnicodeFont() {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
                'This test has not been implemented yet.'
        );
    }

    /**
     * @covers TCPDF::getFontFamilyName
     * @todo   Implement testGetFontFamilyName().
     */
    public function testGetFontFamilyName() {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
                'This test has not been implemented yet.'
        );
    }

    /**
     * @covers TCPDF::startTemplate
     * @todo   Implement testStartTemplate().
     */
    public function testStartTemplate() {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
                'This test has not been implemented yet.'
        );
    }

    /**
     * @covers TCPDF::endTemplate
     * @todo   Implement testEndTemplate().
     */
    public function testEndTemplate() {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
                'This test has not been implemented yet.'
        );
    }

    /**
     * @covers TCPDF::printTemplate
     * @todo   Implement testPrintTemplate().
     */
    public function testPrintTemplate() {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
                'This test has not been implemented yet.'
        );
    }

    /**
     * @covers TCPDF::setFontStretching
     * @todo   Implement testSetFontStretching().
     */
    public function testSetFontStretching() {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
                'This test has not been implemented yet.'
        );
    }

    /**
     * @covers TCPDF::getFontStretching
     * @todo   Implement testGetFontStretching().
     */
    public function testGetFontStretching() {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
                'This test has not been implemented yet.'
        );
    }

    /**
     * @covers TCPDF::setFontSpacing
     * @todo   Implement testSetFontSpacing().
     */
    public function testSetFontSpacing() {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
                'This test has not been implemented yet.'
        );
    }

    /**
     * @covers TCPDF::getFontSpacing
     * @todo   Implement testGetFontSpacing().
     */
    public function testGetFontSpacing() {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
                'This test has not been implemented yet.'
        );
    }

    /**
     * @covers TCPDF::getPageRegions
     * @todo   Implement testGetPageRegions().
     */
    public function testGetPageRegions() {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
                'This test has not been implemented yet.'
        );
    }

    /**
     * @covers TCPDF::setPageRegions
     * @todo   Implement testSetPageRegions().
     */
    public function testSetPageRegions() {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
                'This test has not been implemented yet.'
        );
    }

    /**
     * @covers TCPDF::addPageRegion
     * @todo   Implement testAddPageRegion().
     */
    public function testAddPageRegion() {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
                'This test has not been implemented yet.'
        );
    }

    /**
     * @covers TCPDF::removePageRegion
     * @todo   Implement testRemovePageRegion().
     */
    public function testRemovePageRegion() {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
                'This test has not been implemented yet.'
        );
    }

    /**
     * @covers TCPDF::ImageSVG
     * @todo   Implement testImageSVG().
     */
    public function testImageSVG() {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
                'This test has not been implemented yet.'
        );
    }

}
