<?php

/**
 * Generated by PHPUnit_SkeletonGenerator 1.2.1 on 2014-08-09 at 08:18:05.
 */
class TCPDF_FILTERSTest extends PHPUnit_Framework_TestCase {

    /**
     * @var TCPDF_FILTERS
     */
    protected $object;

    /**
     * Sets up the fixture, for example, opens a network connection.
     * This method is called before a test is executed.
     */
    protected function setUp() {
        $this->object = new TCPDF_FILTERS;
    }

    /**
     * Tears down the fixture, for example, closes a network connection.
     * This method is called after a test is executed.
     */
    protected function tearDown() {
        
    }

    /**
     * @covers TCPDF_FILTERS::getAvailableFilters
     * @todo   Implement testGetAvailableFilters().
     */
    public function testGetAvailableFilters() {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
                'This test has not been implemented yet.'
        );
    }

    /**
     * @covers TCPDF_FILTERS::decodeFilter
     * @todo   Implement testDecodeFilter().
     */
    public function testDecodeFilter() {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
                'This test has not been implemented yet.'
        );
    }

    /**
     * @covers TCPDF_FILTERS::decodeFilterStandard
     * @todo   Implement testDecodeFilterStandard().
     */
    public function testDecodeFilterStandard() {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
                'This test has not been implemented yet.'
        );
    }

    /**
     * @covers TCPDF_FILTERS::decodeFilterASCIIHexDecode
     * @todo   Implement testDecodeFilterASCIIHexDecode().
     */
    public function testDecodeFilterASCIIHexDecode() {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
                'This test has not been implemented yet.'
        );
    }

    /**
     * @covers TCPDF_FILTERS::decodeFilterASCII85Decode
     * @todo   Implement testDecodeFilterASCII85Decode().
     */
    public function testDecodeFilterASCII85Decode() {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
                'This test has not been implemented yet.'
        );
    }

    /**
     * @covers TCPDF_FILTERS::decodeFilterLZWDecode
     * @todo   Implement testDecodeFilterLZWDecode().
     */
    public function testDecodeFilterLZWDecode() {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
                'This test has not been implemented yet.'
        );
    }

    /**
     * @covers TCPDF_FILTERS::decodeFilterFlateDecode
     * @todo   Implement testDecodeFilterFlateDecode().
     */
    public function testDecodeFilterFlateDecode() {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
                'This test has not been implemented yet.'
        );
    }

    /**
     * @covers TCPDF_FILTERS::decodeFilterRunLengthDecode
     * @todo   Implement testDecodeFilterRunLengthDecode().
     */
    public function testDecodeFilterRunLengthDecode() {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
                'This test has not been implemented yet.'
        );
    }

    /**
     * @covers TCPDF_FILTERS::decodeFilterCCITTFaxDecode
     * @todo   Implement testDecodeFilterCCITTFaxDecode().
     */
    public function testDecodeFilterCCITTFaxDecode() {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
                'This test has not been implemented yet.'
        );
    }

    /**
     * @covers TCPDF_FILTERS::decodeFilterJBIG2Decode
     * @todo   Implement testDecodeFilterJBIG2Decode().
     */
    public function testDecodeFilterJBIG2Decode() {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
                'This test has not been implemented yet.'
        );
    }

    /**
     * @covers TCPDF_FILTERS::decodeFilterDCTDecode
     * @todo   Implement testDecodeFilterDCTDecode().
     */
    public function testDecodeFilterDCTDecode() {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
                'This test has not been implemented yet.'
        );
    }

    /**
     * @covers TCPDF_FILTERS::decodeFilterJPXDecode
     * @todo   Implement testDecodeFilterJPXDecode().
     */
    public function testDecodeFilterJPXDecode() {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
                'This test has not been implemented yet.'
        );
    }

    /**
     * @covers TCPDF_FILTERS::decodeFilterCrypt
     * @todo   Implement testDecodeFilterCrypt().
     */
    public function testDecodeFilterCrypt() {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
                'This test has not been implemented yet.'
        );
    }

    /**
     * @covers TCPDF_FILTERS::Error
     * @todo   Implement testError().
     */
    public function testError() {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
                'This test has not been implemented yet.'
        );
    }

}
