<?php

/**
 * Generated by PHPUnit_SkeletonGenerator 1.2.1 on 2014-08-09 at 08:18:39.
 */
class HTMLPurifier_ConfigSchema_InterchangeBuilderTest extends PHPUnit_Framework_TestCase {

    /**
     * @var HTMLPurifier_ConfigSchema_InterchangeBuilder
     */
    protected $object;

    /**
     * Sets up the fixture, for example, opens a network connection.
     * This method is called before a test is executed.
     */
    protected function setUp() {
        $this->object = new HTMLPurifier_ConfigSchema_InterchangeBuilder;
    }

    /**
     * Tears down the fixture, for example, closes a network connection.
     * This method is called after a test is executed.
     */
    protected function tearDown() {
        
    }

    /**
     * @covers HTMLPurifier_ConfigSchema_InterchangeBuilder::buildFromDirectory
     * @todo   Implement testBuildFromDirectory().
     */
    public function testBuildFromDirectory() {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
                'This test has not been implemented yet.'
        );
    }

    /**
     * @covers HTMLPurifier_ConfigSchema_InterchangeBuilder::buildDir
     * @todo   Implement testBuildDir().
     */
    public function testBuildDir() {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
                'This test has not been implemented yet.'
        );
    }

    /**
     * @covers HTMLPurifier_ConfigSchema_InterchangeBuilder::buildFile
     * @todo   Implement testBuildFile().
     */
    public function testBuildFile() {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
                'This test has not been implemented yet.'
        );
    }

    /**
     * @covers HTMLPurifier_ConfigSchema_InterchangeBuilder::build
     * @todo   Implement testBuild().
     */
    public function testBuild() {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
                'This test has not been implemented yet.'
        );
    }

    /**
     * @covers HTMLPurifier_ConfigSchema_InterchangeBuilder::buildDirective
     * @todo   Implement testBuildDirective().
     */
    public function testBuildDirective() {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
                'This test has not been implemented yet.'
        );
    }

}
