<?php

/**
 * Generated by PHPUnit_SkeletonGenerator 1.2.1 on 2014-08-09 at 08:18:37.
 */
class HTMLPurifier_ConfigSchema_InterchangeTest extends PHPUnit_Framework_TestCase {

    /**
     * @var HTMLPurifier_ConfigSchema_Interchange
     */
    protected $object;

    /**
     * Sets up the fixture, for example, opens a network connection.
     * This method is called before a test is executed.
     */
    protected function setUp() {
        $this->object = new HTMLPurifier_ConfigSchema_Interchange;
    }

    /**
     * Tears down the fixture, for example, closes a network connection.
     * This method is called after a test is executed.
     */
    protected function tearDown() {
        
    }

    /**
     * @covers HTMLPurifier_ConfigSchema_Interchange::addDirective
     * @todo   Implement testAddDirective().
     */
    public function testAddDirective() {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
                'This test has not been implemented yet.'
        );
    }

    /**
     * @covers HTMLPurifier_ConfigSchema_Interchange::validate
     * @todo   Implement testValidate().
     */
    public function testValidate() {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
                'This test has not been implemented yet.'
        );
    }

}
