<?php

/**
 * Generated by PHPUnit_SkeletonGenerator 1.2.1 on 2014-08-09 at 08:18:35.
 */
class HTMLPurifier_ConfigSchema_ValidatorAtomTest extends PHPUnit_Framework_TestCase {

    /**
     * @var HTMLPurifier_ConfigSchema_ValidatorAtom
     */
    protected $object;

    /**
     * Sets up the fixture, for example, opens a network connection.
     * This method is called before a test is executed.
     */
    protected function setUp() {
        $this->object = new HTMLPurifier_ConfigSchema_ValidatorAtom;
    }

    /**
     * Tears down the fixture, for example, closes a network connection.
     * This method is called after a test is executed.
     */
    protected function tearDown() {
        
    }

    /**
     * @covers HTMLPurifier_ConfigSchema_ValidatorAtom::assertIsString
     * @todo   Implement testAssertIsString().
     */
    public function testAssertIsString() {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
                'This test has not been implemented yet.'
        );
    }

    /**
     * @covers HTMLPurifier_ConfigSchema_ValidatorAtom::assertIsBool
     * @todo   Implement testAssertIsBool().
     */
    public function testAssertIsBool() {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
                'This test has not been implemented yet.'
        );
    }

    /**
     * @covers HTMLPurifier_ConfigSchema_ValidatorAtom::assertIsArray
     * @todo   Implement testAssertIsArray().
     */
    public function testAssertIsArray() {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
                'This test has not been implemented yet.'
        );
    }

    /**
     * @covers HTMLPurifier_ConfigSchema_ValidatorAtom::assertNotNull
     * @todo   Implement testAssertNotNull().
     */
    public function testAssertNotNull() {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
                'This test has not been implemented yet.'
        );
    }

    /**
     * @covers HTMLPurifier_ConfigSchema_ValidatorAtom::assertAlnum
     * @todo   Implement testAssertAlnum().
     */
    public function testAssertAlnum() {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
                'This test has not been implemented yet.'
        );
    }

    /**
     * @covers HTMLPurifier_ConfigSchema_ValidatorAtom::assertNotEmpty
     * @todo   Implement testAssertNotEmpty().
     */
    public function testAssertNotEmpty() {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
                'This test has not been implemented yet.'
        );
    }

    /**
     * @covers HTMLPurifier_ConfigSchema_ValidatorAtom::assertIsLookup
     * @todo   Implement testAssertIsLookup().
     */
    public function testAssertIsLookup() {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
                'This test has not been implemented yet.'
        );
    }

}
