<?php

/**
 * Generated by PHPUnit_SkeletonGenerator 1.2.1 on 2014-08-09 at 08:18:49.
 */
class SphinxClientTest extends PHPUnit_Framework_TestCase {

    /**
     * @var SphinxClient
     */
    protected $object;

    /**
     * Sets up the fixture, for example, opens a network connection.
     * This method is called before a test is executed.
     */
    protected function setUp() {
        $this->object = new SphinxClient;
    }

    /**
     * Tears down the fixture, for example, closes a network connection.
     * This method is called after a test is executed.
     */
    protected function tearDown() {
        
    }

    /**
     * @covers SphinxClient::__destruct
     * @todo   Implement test__destruct().
     */
    public function test__destruct() {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
                'This test has not been implemented yet.'
        );
    }

    /**
     * @covers SphinxClient::GetLastError
     * @todo   Implement testGetLastError().
     */
    public function testGetLastError() {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
                'This test has not been implemented yet.'
        );
    }

    /**
     * @covers SphinxClient::GetLastWarning
     * @todo   Implement testGetLastWarning().
     */
    public function testGetLastWarning() {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
                'This test has not been implemented yet.'
        );
    }

    /**
     * @covers SphinxClient::IsConnectError
     * @todo   Implement testIsConnectError().
     */
    public function testIsConnectError() {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
                'This test has not been implemented yet.'
        );
    }

    /**
     * @covers SphinxClient::SetServer
     * @todo   Implement testSetServer().
     */
    public function testSetServer() {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
                'This test has not been implemented yet.'
        );
    }

    /**
     * @covers SphinxClient::SetConnectTimeout
     * @todo   Implement testSetConnectTimeout().
     */
    public function testSetConnectTimeout() {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
                'This test has not been implemented yet.'
        );
    }

    /**
     * @covers SphinxClient::_Send
     * @todo   Implement test_Send().
     */
    public function test_Send() {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
                'This test has not been implemented yet.'
        );
    }

    /**
     * @covers SphinxClient::_MBPush
     * @todo   Implement test_MBPush().
     */
    public function test_MBPush() {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
                'This test has not been implemented yet.'
        );
    }

    /**
     * @covers SphinxClient::_MBPop
     * @todo   Implement test_MBPop().
     */
    public function test_MBPop() {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
                'This test has not been implemented yet.'
        );
    }

    /**
     * @covers SphinxClient::_Connect
     * @todo   Implement test_Connect().
     */
    public function test_Connect() {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
                'This test has not been implemented yet.'
        );
    }

    /**
     * @covers SphinxClient::_GetResponse
     * @todo   Implement test_GetResponse().
     */
    public function test_GetResponse() {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
                'This test has not been implemented yet.'
        );
    }

    /**
     * @covers SphinxClient::SetLimits
     * @todo   Implement testSetLimits().
     */
    public function testSetLimits() {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
                'This test has not been implemented yet.'
        );
    }

    /**
     * @covers SphinxClient::SetMaxQueryTime
     * @todo   Implement testSetMaxQueryTime().
     */
    public function testSetMaxQueryTime() {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
                'This test has not been implemented yet.'
        );
    }

    /**
     * @covers SphinxClient::SetMatchMode
     * @todo   Implement testSetMatchMode().
     */
    public function testSetMatchMode() {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
                'This test has not been implemented yet.'
        );
    }

    /**
     * @covers SphinxClient::SetRankingMode
     * @todo   Implement testSetRankingMode().
     */
    public function testSetRankingMode() {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
                'This test has not been implemented yet.'
        );
    }

    /**
     * @covers SphinxClient::SetSortMode
     * @todo   Implement testSetSortMode().
     */
    public function testSetSortMode() {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
                'This test has not been implemented yet.'
        );
    }

    /**
     * @covers SphinxClient::SetWeights
     * @todo   Implement testSetWeights().
     */
    public function testSetWeights() {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
                'This test has not been implemented yet.'
        );
    }

    /**
     * @covers SphinxClient::SetFieldWeights
     * @todo   Implement testSetFieldWeights().
     */
    public function testSetFieldWeights() {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
                'This test has not been implemented yet.'
        );
    }

    /**
     * @covers SphinxClient::SetIndexWeights
     * @todo   Implement testSetIndexWeights().
     */
    public function testSetIndexWeights() {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
                'This test has not been implemented yet.'
        );
    }

    /**
     * @covers SphinxClient::SetIDRange
     * @todo   Implement testSetIDRange().
     */
    public function testSetIDRange() {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
                'This test has not been implemented yet.'
        );
    }

    /**
     * @covers SphinxClient::SetFilter
     * @todo   Implement testSetFilter().
     */
    public function testSetFilter() {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
                'This test has not been implemented yet.'
        );
    }

    /**
     * @covers SphinxClient::SetFilterRange
     * @todo   Implement testSetFilterRange().
     */
    public function testSetFilterRange() {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
                'This test has not been implemented yet.'
        );
    }

    /**
     * @covers SphinxClient::SetFilterFloatRange
     * @todo   Implement testSetFilterFloatRange().
     */
    public function testSetFilterFloatRange() {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
                'This test has not been implemented yet.'
        );
    }

    /**
     * @covers SphinxClient::SetGeoAnchor
     * @todo   Implement testSetGeoAnchor().
     */
    public function testSetGeoAnchor() {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
                'This test has not been implemented yet.'
        );
    }

    /**
     * @covers SphinxClient::SetGroupBy
     * @todo   Implement testSetGroupBy().
     */
    public function testSetGroupBy() {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
                'This test has not been implemented yet.'
        );
    }

    /**
     * @covers SphinxClient::SetGroupDistinct
     * @todo   Implement testSetGroupDistinct().
     */
    public function testSetGroupDistinct() {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
                'This test has not been implemented yet.'
        );
    }

    /**
     * @covers SphinxClient::SetRetries
     * @todo   Implement testSetRetries().
     */
    public function testSetRetries() {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
                'This test has not been implemented yet.'
        );
    }

    /**
     * @covers SphinxClient::SetArrayResult
     * @todo   Implement testSetArrayResult().
     */
    public function testSetArrayResult() {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
                'This test has not been implemented yet.'
        );
    }

    /**
     * @covers SphinxClient::SetOverride
     * @todo   Implement testSetOverride().
     */
    public function testSetOverride() {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
                'This test has not been implemented yet.'
        );
    }

    /**
     * @covers SphinxClient::SetSelect
     * @todo   Implement testSetSelect().
     */
    public function testSetSelect() {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
                'This test has not been implemented yet.'
        );
    }

    /**
     * @covers SphinxClient::ResetFilters
     * @todo   Implement testResetFilters().
     */
    public function testResetFilters() {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
                'This test has not been implemented yet.'
        );
    }

    /**
     * @covers SphinxClient::ResetGroupBy
     * @todo   Implement testResetGroupBy().
     */
    public function testResetGroupBy() {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
                'This test has not been implemented yet.'
        );
    }

    /**
     * @covers SphinxClient::ResetOverrides
     * @todo   Implement testResetOverrides().
     */
    public function testResetOverrides() {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
                'This test has not been implemented yet.'
        );
    }

    /**
     * @covers SphinxClient::Query
     * @todo   Implement testQuery().
     */
    public function testQuery() {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
                'This test has not been implemented yet.'
        );
    }

    /**
     * @covers SphinxClient::_PackFloat
     * @todo   Implement test_PackFloat().
     */
    public function test_PackFloat() {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
                'This test has not been implemented yet.'
        );
    }

    /**
     * @covers SphinxClient::AddQuery
     * @todo   Implement testAddQuery().
     */
    public function testAddQuery() {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
                'This test has not been implemented yet.'
        );
    }

    /**
     * @covers SphinxClient::RunQueries
     * @todo   Implement testRunQueries().
     */
    public function testRunQueries() {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
                'This test has not been implemented yet.'
        );
    }

    /**
     * @covers SphinxClient::_ParseSearchResponse
     * @todo   Implement test_ParseSearchResponse().
     */
    public function test_ParseSearchResponse() {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
                'This test has not been implemented yet.'
        );
    }

    /**
     * @covers SphinxClient::BuildExcerpts
     * @todo   Implement testBuildExcerpts().
     */
    public function testBuildExcerpts() {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
                'This test has not been implemented yet.'
        );
    }

    /**
     * @covers SphinxClient::BuildKeywords
     * @todo   Implement testBuildKeywords().
     */
    public function testBuildKeywords() {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
                'This test has not been implemented yet.'
        );
    }

    /**
     * @covers SphinxClient::EscapeString
     * @todo   Implement testEscapeString().
     */
    public function testEscapeString() {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
                'This test has not been implemented yet.'
        );
    }

    /**
     * @covers SphinxClient::UpdateAttributes
     * @todo   Implement testUpdateAttributes().
     */
    public function testUpdateAttributes() {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
                'This test has not been implemented yet.'
        );
    }

    /**
     * @covers SphinxClient::Open
     * @todo   Implement testOpen().
     */
    public function testOpen() {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
                'This test has not been implemented yet.'
        );
    }

    /**
     * @covers SphinxClient::Close
     * @todo   Implement testClose().
     */
    public function testClose() {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
                'This test has not been implemented yet.'
        );
    }

    /**
     * @covers SphinxClient::Status
     * @todo   Implement testStatus().
     */
    public function testStatus() {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
                'This test has not been implemented yet.'
        );
    }

}
