<?php

/**
 * Generated by PHPUnit_SkeletonGenerator 1.2.1 on 2014-08-09 at 08:19:02.
 */
class SpTest extends PHPUnit_Framework_TestCase {

    /**
     * @var Sp
     */
    protected $object;

    /**
     * Sets up the fixture, for example, opens a network connection.
     * This method is called before a test is executed.
     */
    protected function setUp() {
        $this->object = new Sp;
    }

    /**
     * Tears down the fixture, for example, closes a network connection.
     * This method is called after a test is executed.
     */
    protected function tearDown() {
        
    }

    /**
     * @covers Sp::sp_ad_container_save
     * @todo   Implement testSp_ad_container_save().
     */
    public function testSp_ad_container_save() {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
                'This test has not been implemented yet.'
        );
    }

    /**
     * @covers Sp::sp_ad_container_get_list
     * @todo   Implement testSp_ad_container_get_list().
     */
    public function testSp_ad_container_get_list() {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
                'This test has not been implemented yet.'
        );
    }

    /**
     * @covers Sp::sp_ad_container_get_list_by_ids
     * @todo   Implement testSp_ad_container_get_list_by_ids().
     */
    public function testSp_ad_container_get_list_by_ids() {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
                'This test has not been implemented yet.'
        );
    }

    /**
     * @covers Sp::sp_ad_banner_get_list
     * @todo   Implement testSp_ad_banner_get_list().
     */
    public function testSp_ad_banner_get_list() {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
                'This test has not been implemented yet.'
        );
    }

    /**
     * @covers Sp::sp_ad_banner_get_list_by_ids
     * @todo   Implement testSp_ad_banner_get_list_by_ids().
     */
    public function testSp_ad_banner_get_list_by_ids() {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
                'This test has not been implemented yet.'
        );
    }

    /**
     * @covers Sp::sp_ad_banner_save
     * @todo   Implement testSp_ad_banner_save().
     */
    public function testSp_ad_banner_save() {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
                'This test has not been implemented yet.'
        );
    }

    /**
     * @covers Sp::sp_ad_banner_remove_urls
     * @todo   Implement testSp_ad_banner_remove_urls().
     */
    public function testSp_ad_banner_remove_urls() {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
                'This test has not been implemented yet.'
        );
    }

    /**
     * @covers Sp::sp_ad_banner_save_url
     * @todo   Implement testSp_ad_banner_save_url().
     */
    public function testSp_ad_banner_save_url() {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
                'This test has not been implemented yet.'
        );
    }

    /**
     * @covers Sp::sp_ad_banner_get_by_guid
     * @todo   Implement testSp_ad_banner_get_by_guid().
     */
    public function testSp_ad_banner_get_by_guid() {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
                'This test has not been implemented yet.'
        );
    }

    /**
     * @covers Sp::sp_ad_banner_register_show
     * @todo   Implement testSp_ad_banner_register_show().
     */
    public function testSp_ad_banner_register_show() {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
                'This test has not been implemented yet.'
        );
    }

    /**
     * @covers Sp::sp_ad_banner_get_quick_by_ids
     * @todo   Implement testSp_ad_banner_get_quick_by_ids().
     */
    public function testSp_ad_banner_get_quick_by_ids() {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
                'This test has not been implemented yet.'
        );
    }

    /**
     * @covers Sp::sp_ad_banner_get_urls
     * @todo   Implement testSp_ad_banner_get_urls().
     */
    public function testSp_ad_banner_get_urls() {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
                'This test has not been implemented yet.'
        );
    }

}
