<?php

/**
 * Generated by PHPUnit_SkeletonGenerator 1.2.1 on 2014-08-09 at 08:18:41.
 */
class HTMLPurifier_ConfigSchema_Interchange_DirectiveTest extends PHPUnit_Framework_TestCase {

    /**
     * @var HTMLPurifier_ConfigSchema_Interchange_Directive
     */
    protected $object;

    /**
     * Sets up the fixture, for example, opens a network connection.
     * This method is called before a test is executed.
     */
    protected function setUp() {
        $this->object = new HTMLPurifier_ConfigSchema_Interchange_Directive;
    }

    /**
     * Tears down the fixture, for example, closes a network connection.
     * This method is called after a test is executed.
     */
    protected function tearDown() {
        
    }

}
