<?php

/**
 * Generated by PHPUnit_SkeletonGenerator 1.2.1 on 2014-08-09 at 08:18:40.
 */
class HTMLPurifier_ConfigSchema_Interchange_IdTest extends PHPUnit_Framework_TestCase {

    /**
     * @var HTMLPurifier_ConfigSchema_Interchange_Id
     */
    protected $object;

    /**
     * Sets up the fixture, for example, opens a network connection.
     * This method is called before a test is executed.
     */
    protected function setUp() {
        $this->object = new HTMLPurifier_ConfigSchema_Interchange_Id;
    }

    /**
     * Tears down the fixture, for example, closes a network connection.
     * This method is called after a test is executed.
     */
    protected function tearDown() {
        
    }

    /**
     * @covers HTMLPurifier_ConfigSchema_Interchange_Id::toString
     * @todo   Implement testToString().
     */
    public function testToString() {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
                'This test has not been implemented yet.'
        );
    }

    /**
     * @covers HTMLPurifier_ConfigSchema_Interchange_Id::getRootNamespace
     * @todo   Implement testGetRootNamespace().
     */
    public function testGetRootNamespace() {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
                'This test has not been implemented yet.'
        );
    }

    /**
     * @covers HTMLPurifier_ConfigSchema_Interchange_Id::getDirective
     * @todo   Implement testGetDirective().
     */
    public function testGetDirective() {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
                'This test has not been implemented yet.'
        );
    }

    /**
     * @covers HTMLPurifier_ConfigSchema_Interchange_Id::make
     * @todo   Implement testMake().
     */
    public function testMake() {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
                'This test has not been implemented yet.'
        );
    }

}
