<?php

/**
 * Generated by PHPUnit_SkeletonGenerator 1.2.1 on 2014-08-09 at 08:18:45.
 */
class HTMLPurifier_AttrDef_CSS_BackgroundPositionTest extends PHPUnit_Framework_TestCase {

    /**
     * @var HTMLPurifier_AttrDef_CSS_BackgroundPosition
     */
    protected $object;

    /**
     * Sets up the fixture, for example, opens a network connection.
     * This method is called before a test is executed.
     */
    protected function setUp() {
        $this->object = new HTMLPurifier_AttrDef_CSS_BackgroundPosition;
    }

    /**
     * Tears down the fixture, for example, closes a network connection.
     * This method is called after a test is executed.
     */
    protected function tearDown() {
        
    }

    /**
     * @covers HTMLPurifier_AttrDef_CSS_BackgroundPosition::validate
     * @todo   Implement testValidate().
     */
    public function testValidate() {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
                'This test has not been implemented yet.'
        );
    }

}
