<?php

/**
 * Generated by PHPUnit_SkeletonGenerator 1.2.1 on 2014-08-09 at 08:17:37.
 */
class Smarty_Internal_RegisterTest extends PHPUnit_Framework_TestCase {

    /**
     * @var Smarty_Internal_Register
     */
    protected $object;

    /**
     * Sets up the fixture, for example, opens a network connection.
     * This method is called before a test is executed.
     */
    protected function setUp() {
        $this->object = new Smarty_Internal_Register;
    }

    /**
     * Tears down the fixture, for example, closes a network connection.
     * This method is called after a test is executed.
     */
    protected function tearDown() {
        
    }

    /**
     * @covers Smarty_Internal_Register::block
     * @todo   Implement testBlock().
     */
    public function testBlock() {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
                'This test has not been implemented yet.'
        );
    }

    /**
     * @covers Smarty_Internal_Register::compilerFunction
     * @todo   Implement testCompilerFunction().
     */
    public function testCompilerFunction() {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
                'This test has not been implemented yet.'
        );
    }

    /**
     * @covers Smarty_Internal_Register::templateFunction
     * @todo   Implement testTemplateFunction().
     */
    public function testTemplateFunction() {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
                'This test has not been implemented yet.'
        );
    }

    /**
     * @covers Smarty_Internal_Register::modifier
     * @todo   Implement testModifier().
     */
    public function testModifier() {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
                'This test has not been implemented yet.'
        );
    }

    /**
     * @covers Smarty_Internal_Register::templateObject
     * @todo   Implement testTemplateObject().
     */
    public function testTemplateObject() {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
                'This test has not been implemented yet.'
        );
    }

    /**
     * @covers Smarty_Internal_Register::outputFilter
     * @todo   Implement testOutputFilter().
     */
    public function testOutputFilter() {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
                'This test has not been implemented yet.'
        );
    }

    /**
     * @covers Smarty_Internal_Register::postFilter
     * @todo   Implement testPostFilter().
     */
    public function testPostFilter() {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
                'This test has not been implemented yet.'
        );
    }

    /**
     * @covers Smarty_Internal_Register::preFilter
     * @todo   Implement testPreFilter().
     */
    public function testPreFilter() {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
                'This test has not been implemented yet.'
        );
    }

    /**
     * @covers Smarty_Internal_Register::resource
     * @todo   Implement testResource().
     */
    public function testResource() {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
                'This test has not been implemented yet.'
        );
    }

    /**
     * @covers Smarty_Internal_Register::variableFilter
     * @todo   Implement testVariableFilter().
     */
    public function testVariableFilter() {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
                'This test has not been implemented yet.'
        );
    }

    /**
     * @covers Smarty_Internal_Register::defaultPluginHandler
     * @todo   Implement testDefaultPluginHandler().
     */
    public function testDefaultPluginHandler() {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
                'This test has not been implemented yet.'
        );
    }

    /**
     * @covers Smarty_Internal_Register::defaultTemplateHandler
     * @todo   Implement testDefaultTemplateHandler().
     */
    public function testDefaultTemplateHandler() {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
                'This test has not been implemented yet.'
        );
    }

}
