<?php

/**
 * Generated by PHPUnit_SkeletonGenerator 1.2.1 on 2014-08-09 at 08:17:31.
 */
class Smarty_Internal_ConfigfilelexerTest extends PHPUnit_Framework_TestCase {

    /**
     * @var Smarty_Internal_Configfilelexer
     */
    protected $object;

    /**
     * Sets up the fixture, for example, opens a network connection.
     * This method is called before a test is executed.
     */
    protected function setUp() {
        $this->object = new Smarty_Internal_Configfilelexer;
    }

    /**
     * Tears down the fixture, for example, closes a network connection.
     * This method is called after a test is executed.
     */
    protected function tearDown() {
        
    }

    /**
     * @covers Smarty_Internal_Configfilelexer::instance
     * @todo   Implement testInstance().
     */
    public function testInstance() {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
                'This test has not been implemented yet.'
        );
    }

    /**
     * @covers Smarty_Internal_Configfilelexer::yylex
     * @todo   Implement testYylex().
     */
    public function testYylex() {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
                'This test has not been implemented yet.'
        );
    }

    /**
     * @covers Smarty_Internal_Configfilelexer::yypushstate
     * @todo   Implement testYypushstate().
     */
    public function testYypushstate() {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
                'This test has not been implemented yet.'
        );
    }

    /**
     * @covers Smarty_Internal_Configfilelexer::yypopstate
     * @todo   Implement testYypopstate().
     */
    public function testYypopstate() {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
                'This test has not been implemented yet.'
        );
    }

    /**
     * @covers Smarty_Internal_Configfilelexer::yybegin
     * @todo   Implement testYybegin().
     */
    public function testYybegin() {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
                'This test has not been implemented yet.'
        );
    }

    /**
     * @covers Smarty_Internal_Configfilelexer::yylex1
     * @todo   Implement testYylex1().
     */
    public function testYylex1() {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
                'This test has not been implemented yet.'
        );
    }

    /**
     * @covers Smarty_Internal_Configfilelexer::yy_r1_1
     * @todo   Implement testYy_r1_1().
     */
    public function testYy_r1_1() {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
                'This test has not been implemented yet.'
        );
    }

    /**
     * @covers Smarty_Internal_Configfilelexer::yy_r1_2
     * @todo   Implement testYy_r1_2().
     */
    public function testYy_r1_2() {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
                'This test has not been implemented yet.'
        );
    }

    /**
     * @covers Smarty_Internal_Configfilelexer::yy_r1_3
     * @todo   Implement testYy_r1_3().
     */
    public function testYy_r1_3() {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
                'This test has not been implemented yet.'
        );
    }

    /**
     * @covers Smarty_Internal_Configfilelexer::yy_r1_4
     * @todo   Implement testYy_r1_4().
     */
    public function testYy_r1_4() {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
                'This test has not been implemented yet.'
        );
    }

    /**
     * @covers Smarty_Internal_Configfilelexer::yy_r1_5
     * @todo   Implement testYy_r1_5().
     */
    public function testYy_r1_5() {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
                'This test has not been implemented yet.'
        );
    }

    /**
     * @covers Smarty_Internal_Configfilelexer::yy_r1_6
     * @todo   Implement testYy_r1_6().
     */
    public function testYy_r1_6() {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
                'This test has not been implemented yet.'
        );
    }

    /**
     * @covers Smarty_Internal_Configfilelexer::yy_r1_7
     * @todo   Implement testYy_r1_7().
     */
    public function testYy_r1_7() {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
                'This test has not been implemented yet.'
        );
    }

    /**
     * @covers Smarty_Internal_Configfilelexer::yylex2
     * @todo   Implement testYylex2().
     */
    public function testYylex2() {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
                'This test has not been implemented yet.'
        );
    }

    /**
     * @covers Smarty_Internal_Configfilelexer::yy_r2_1
     * @todo   Implement testYy_r2_1().
     */
    public function testYy_r2_1() {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
                'This test has not been implemented yet.'
        );
    }

    /**
     * @covers Smarty_Internal_Configfilelexer::yy_r2_2
     * @todo   Implement testYy_r2_2().
     */
    public function testYy_r2_2() {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
                'This test has not been implemented yet.'
        );
    }

    /**
     * @covers Smarty_Internal_Configfilelexer::yy_r2_3
     * @todo   Implement testYy_r2_3().
     */
    public function testYy_r2_3() {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
                'This test has not been implemented yet.'
        );
    }

    /**
     * @covers Smarty_Internal_Configfilelexer::yy_r2_4
     * @todo   Implement testYy_r2_4().
     */
    public function testYy_r2_4() {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
                'This test has not been implemented yet.'
        );
    }

    /**
     * @covers Smarty_Internal_Configfilelexer::yy_r2_5
     * @todo   Implement testYy_r2_5().
     */
    public function testYy_r2_5() {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
                'This test has not been implemented yet.'
        );
    }

    /**
     * @covers Smarty_Internal_Configfilelexer::yy_r2_6
     * @todo   Implement testYy_r2_6().
     */
    public function testYy_r2_6() {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
                'This test has not been implemented yet.'
        );
    }

    /**
     * @covers Smarty_Internal_Configfilelexer::yy_r2_7
     * @todo   Implement testYy_r2_7().
     */
    public function testYy_r2_7() {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
                'This test has not been implemented yet.'
        );
    }

    /**
     * @covers Smarty_Internal_Configfilelexer::yy_r2_8
     * @todo   Implement testYy_r2_8().
     */
    public function testYy_r2_8() {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
                'This test has not been implemented yet.'
        );
    }

    /**
     * @covers Smarty_Internal_Configfilelexer::yy_r2_9
     * @todo   Implement testYy_r2_9().
     */
    public function testYy_r2_9() {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
                'This test has not been implemented yet.'
        );
    }

    /**
     * @covers Smarty_Internal_Configfilelexer::yylex3
     * @todo   Implement testYylex3().
     */
    public function testYylex3() {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
                'This test has not been implemented yet.'
        );
    }

    /**
     * @covers Smarty_Internal_Configfilelexer::yy_r3_1
     * @todo   Implement testYy_r3_1().
     */
    public function testYy_r3_1() {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
                'This test has not been implemented yet.'
        );
    }

    /**
     * @covers Smarty_Internal_Configfilelexer::yylex4
     * @todo   Implement testYylex4().
     */
    public function testYylex4() {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
                'This test has not been implemented yet.'
        );
    }

    /**
     * @covers Smarty_Internal_Configfilelexer::yy_r4_1
     * @todo   Implement testYy_r4_1().
     */
    public function testYy_r4_1() {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
                'This test has not been implemented yet.'
        );
    }

    /**
     * @covers Smarty_Internal_Configfilelexer::yy_r4_2
     * @todo   Implement testYy_r4_2().
     */
    public function testYy_r4_2() {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
                'This test has not been implemented yet.'
        );
    }

    /**
     * @covers Smarty_Internal_Configfilelexer::yy_r4_3
     * @todo   Implement testYy_r4_3().
     */
    public function testYy_r4_3() {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
                'This test has not been implemented yet.'
        );
    }

    /**
     * @covers Smarty_Internal_Configfilelexer::yylex5
     * @todo   Implement testYylex5().
     */
    public function testYylex5() {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
                'This test has not been implemented yet.'
        );
    }

    /**
     * @covers Smarty_Internal_Configfilelexer::yy_r5_1
     * @todo   Implement testYy_r5_1().
     */
    public function testYy_r5_1() {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
                'This test has not been implemented yet.'
        );
    }

    /**
     * @covers Smarty_Internal_Configfilelexer::yy_r5_2
     * @todo   Implement testYy_r5_2().
     */
    public function testYy_r5_2() {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
                'This test has not been implemented yet.'
        );
    }

}
