<?php

/**
 * Generated by PHPUnit_SkeletonGenerator 1.2.1 on 2014-08-09 at 08:17:32.
 */
class Smarty_Internal_Resource_ExtendsTest extends PHPUnit_Framework_TestCase {

    /**
     * @var Smarty_Internal_Resource_Extends
     */
    protected $object;

    /**
     * Sets up the fixture, for example, opens a network connection.
     * This method is called before a test is executed.
     */
    protected function setUp() {
        $this->object = new Smarty_Internal_Resource_Extends;
    }

    /**
     * Tears down the fixture, for example, closes a network connection.
     * This method is called after a test is executed.
     */
    protected function tearDown() {
        
    }

    /**
     * @covers Smarty_Internal_Resource_Extends::isExisting
     * @todo   Implement testIsExisting().
     */
    public function testIsExisting() {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
                'This test has not been implemented yet.'
        );
    }

    /**
     * @covers Smarty_Internal_Resource_Extends::getTemplateFilepath
     * @todo   Implement testGetTemplateFilepath().
     */
    public function testGetTemplateFilepath() {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
                'This test has not been implemented yet.'
        );
    }

    /**
     * @covers Smarty_Internal_Resource_Extends::getTemplateTimestamp
     * @todo   Implement testGetTemplateTimestamp().
     */
    public function testGetTemplateTimestamp() {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
                'This test has not been implemented yet.'
        );
    }

    /**
     * @covers Smarty_Internal_Resource_Extends::getTemplateSource
     * @todo   Implement testGetTemplateSource().
     */
    public function testGetTemplateSource() {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
                'This test has not been implemented yet.'
        );
    }

    /**
     * @covers Smarty_Internal_Resource_Extends::getCompiledFilepath
     * @todo   Implement testGetCompiledFilepath().
     */
    public function testGetCompiledFilepath() {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
                'This test has not been implemented yet.'
        );
    }

}
