<?php

/**
 * Generated by PHPUnit_SkeletonGenerator 1.2.1 on 2014-08-09 at 08:17:16.
 */
class Smarty_Internal_Config_File_CompilerTest extends PHPUnit_Framework_TestCase {

    /**
     * @var Smarty_Internal_Config_File_Compiler
     */
    protected $object;

    /**
     * Sets up the fixture, for example, opens a network connection.
     * This method is called before a test is executed.
     */
    protected function setUp() {
        $this->object = new Smarty_Internal_Config_File_Compiler;
    }

    /**
     * Tears down the fixture, for example, closes a network connection.
     * This method is called after a test is executed.
     */
    protected function tearDown() {
        
    }

    /**
     * @covers Smarty_Internal_Config_File_Compiler::compileSource
     * @todo   Implement testCompileSource().
     */
    public function testCompileSource() {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
                'This test has not been implemented yet.'
        );
    }

    /**
     * @covers Smarty_Internal_Config_File_Compiler::trigger_config_file_error
     * @todo   Implement testTrigger_config_file_error().
     */
    public function testTrigger_config_file_error() {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
                'This test has not been implemented yet.'
        );
    }

}
