<?php

/**
 * Generated by PHPUnit_SkeletonGenerator 1.2.1 on 2014-08-09 at 08:17:45.
 */
class Smarty_Internal_UtilityTest extends PHPUnit_Framework_TestCase {

    /**
     * @var Smarty_Internal_Utility
     */
    protected $object;

    /**
     * Sets up the fixture, for example, opens a network connection.
     * This method is called before a test is executed.
     */
    protected function setUp() {
        $this->object = new Smarty_Internal_Utility;
    }

    /**
     * Tears down the fixture, for example, closes a network connection.
     * This method is called after a test is executed.
     */
    protected function tearDown() {
        
    }

    /**
     * @covers Smarty_Internal_Utility::compileAllTemplates
     * @todo   Implement testCompileAllTemplates().
     */
    public function testCompileAllTemplates() {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
                'This test has not been implemented yet.'
        );
    }

    /**
     * @covers Smarty_Internal_Utility::compileAllConfig
     * @todo   Implement testCompileAllConfig().
     */
    public function testCompileAllConfig() {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
                'This test has not been implemented yet.'
        );
    }

    /**
     * @covers Smarty_Internal_Utility::clearCompiledTemplate
     * @todo   Implement testClearCompiledTemplate().
     */
    public function testClearCompiledTemplate() {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
                'This test has not been implemented yet.'
        );
    }

    /**
     * @covers Smarty_Internal_Utility::testInstall
     * @todo   Implement testTestInstall().
     */
    public function testTestInstall() {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
                'This test has not been implemented yet.'
        );
    }

    /**
     * @covers Smarty_Internal_Utility::_get_time
     * @todo   Implement test_get_time().
     */
    public function test_get_time() {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
                'This test has not been implemented yet.'
        );
    }

}
