<?php

/**
 * Generated by PHPUnit_SkeletonGenerator 1.2.1 on 2014-08-09 at 08:17:39.
 */
class Smarty_Internal_TemplatelexerTest extends PHPUnit_Framework_TestCase {

    /**
     * @var Smarty_Internal_Templatelexer
     */
    protected $object;

    /**
     * Sets up the fixture, for example, opens a network connection.
     * This method is called before a test is executed.
     */
    protected function setUp() {
        $this->object = new Smarty_Internal_Templatelexer;
    }

    /**
     * Tears down the fixture, for example, closes a network connection.
     * This method is called after a test is executed.
     */
    protected function tearDown() {
        
    }

    /**
     * @covers Smarty_Internal_Templatelexer::instance
     * @todo   Implement testInstance().
     */
    public function testInstance() {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
                'This test has not been implemented yet.'
        );
    }

    /**
     * @covers Smarty_Internal_Templatelexer::yylex
     * @todo   Implement testYylex().
     */
    public function testYylex() {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
                'This test has not been implemented yet.'
        );
    }

    /**
     * @covers Smarty_Internal_Templatelexer::yypushstate
     * @todo   Implement testYypushstate().
     */
    public function testYypushstate() {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
                'This test has not been implemented yet.'
        );
    }

    /**
     * @covers Smarty_Internal_Templatelexer::yypopstate
     * @todo   Implement testYypopstate().
     */
    public function testYypopstate() {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
                'This test has not been implemented yet.'
        );
    }

    /**
     * @covers Smarty_Internal_Templatelexer::yybegin
     * @todo   Implement testYybegin().
     */
    public function testYybegin() {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
                'This test has not been implemented yet.'
        );
    }

    /**
     * @covers Smarty_Internal_Templatelexer::yylex1
     * @todo   Implement testYylex1().
     */
    public function testYylex1() {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
                'This test has not been implemented yet.'
        );
    }

    /**
     * @covers Smarty_Internal_Templatelexer::yy_r1_1
     * @todo   Implement testYy_r1_1().
     */
    public function testYy_r1_1() {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
                'This test has not been implemented yet.'
        );
    }

    /**
     * @covers Smarty_Internal_Templatelexer::yy_r1_2
     * @todo   Implement testYy_r1_2().
     */
    public function testYy_r1_2() {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
                'This test has not been implemented yet.'
        );
    }

    /**
     * @covers Smarty_Internal_Templatelexer::yy_r1_4
     * @todo   Implement testYy_r1_4().
     */
    public function testYy_r1_4() {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
                'This test has not been implemented yet.'
        );
    }

    /**
     * @covers Smarty_Internal_Templatelexer::yy_r1_5
     * @todo   Implement testYy_r1_5().
     */
    public function testYy_r1_5() {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
                'This test has not been implemented yet.'
        );
    }

    /**
     * @covers Smarty_Internal_Templatelexer::yy_r1_6
     * @todo   Implement testYy_r1_6().
     */
    public function testYy_r1_6() {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
                'This test has not been implemented yet.'
        );
    }

    /**
     * @covers Smarty_Internal_Templatelexer::yy_r1_7
     * @todo   Implement testYy_r1_7().
     */
    public function testYy_r1_7() {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
                'This test has not been implemented yet.'
        );
    }

    /**
     * @covers Smarty_Internal_Templatelexer::yy_r1_8
     * @todo   Implement testYy_r1_8().
     */
    public function testYy_r1_8() {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
                'This test has not been implemented yet.'
        );
    }

    /**
     * @covers Smarty_Internal_Templatelexer::yy_r1_9
     * @todo   Implement testYy_r1_9().
     */
    public function testYy_r1_9() {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
                'This test has not been implemented yet.'
        );
    }

    /**
     * @covers Smarty_Internal_Templatelexer::yy_r1_10
     * @todo   Implement testYy_r1_10().
     */
    public function testYy_r1_10() {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
                'This test has not been implemented yet.'
        );
    }

    /**
     * @covers Smarty_Internal_Templatelexer::yy_r1_11
     * @todo   Implement testYy_r1_11().
     */
    public function testYy_r1_11() {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
                'This test has not been implemented yet.'
        );
    }

    /**
     * @covers Smarty_Internal_Templatelexer::yy_r1_12
     * @todo   Implement testYy_r1_12().
     */
    public function testYy_r1_12() {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
                'This test has not been implemented yet.'
        );
    }

    /**
     * @covers Smarty_Internal_Templatelexer::yy_r1_13
     * @todo   Implement testYy_r1_13().
     */
    public function testYy_r1_13() {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
                'This test has not been implemented yet.'
        );
    }

    /**
     * @covers Smarty_Internal_Templatelexer::yy_r1_14
     * @todo   Implement testYy_r1_14().
     */
    public function testYy_r1_14() {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
                'This test has not been implemented yet.'
        );
    }

    /**
     * @covers Smarty_Internal_Templatelexer::yy_r1_17
     * @todo   Implement testYy_r1_17().
     */
    public function testYy_r1_17() {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
                'This test has not been implemented yet.'
        );
    }

    /**
     * @covers Smarty_Internal_Templatelexer::yylex2
     * @todo   Implement testYylex2().
     */
    public function testYylex2() {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
                'This test has not been implemented yet.'
        );
    }

    /**
     * @covers Smarty_Internal_Templatelexer::yy_r2_1
     * @todo   Implement testYy_r2_1().
     */
    public function testYy_r2_1() {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
                'This test has not been implemented yet.'
        );
    }

    /**
     * @covers Smarty_Internal_Templatelexer::yy_r2_2
     * @todo   Implement testYy_r2_2().
     */
    public function testYy_r2_2() {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
                'This test has not been implemented yet.'
        );
    }

    /**
     * @covers Smarty_Internal_Templatelexer::yy_r2_3
     * @todo   Implement testYy_r2_3().
     */
    public function testYy_r2_3() {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
                'This test has not been implemented yet.'
        );
    }

    /**
     * @covers Smarty_Internal_Templatelexer::yy_r2_4
     * @todo   Implement testYy_r2_4().
     */
    public function testYy_r2_4() {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
                'This test has not been implemented yet.'
        );
    }

    /**
     * @covers Smarty_Internal_Templatelexer::yy_r2_5
     * @todo   Implement testYy_r2_5().
     */
    public function testYy_r2_5() {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
                'This test has not been implemented yet.'
        );
    }

    /**
     * @covers Smarty_Internal_Templatelexer::yy_r2_6
     * @todo   Implement testYy_r2_6().
     */
    public function testYy_r2_6() {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
                'This test has not been implemented yet.'
        );
    }

    /**
     * @covers Smarty_Internal_Templatelexer::yy_r2_7
     * @todo   Implement testYy_r2_7().
     */
    public function testYy_r2_7() {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
                'This test has not been implemented yet.'
        );
    }

    /**
     * @covers Smarty_Internal_Templatelexer::yy_r2_8
     * @todo   Implement testYy_r2_8().
     */
    public function testYy_r2_8() {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
                'This test has not been implemented yet.'
        );
    }

    /**
     * @covers Smarty_Internal_Templatelexer::yy_r2_9
     * @todo   Implement testYy_r2_9().
     */
    public function testYy_r2_9() {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
                'This test has not been implemented yet.'
        );
    }

    /**
     * @covers Smarty_Internal_Templatelexer::yy_r2_11
     * @todo   Implement testYy_r2_11().
     */
    public function testYy_r2_11() {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
                'This test has not been implemented yet.'
        );
    }

    /**
     * @covers Smarty_Internal_Templatelexer::yy_r2_13
     * @todo   Implement testYy_r2_13().
     */
    public function testYy_r2_13() {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
                'This test has not been implemented yet.'
        );
    }

    /**
     * @covers Smarty_Internal_Templatelexer::yy_r2_15
     * @todo   Implement testYy_r2_15().
     */
    public function testYy_r2_15() {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
                'This test has not been implemented yet.'
        );
    }

    /**
     * @covers Smarty_Internal_Templatelexer::yy_r2_16
     * @todo   Implement testYy_r2_16().
     */
    public function testYy_r2_16() {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
                'This test has not been implemented yet.'
        );
    }

    /**
     * @covers Smarty_Internal_Templatelexer::yy_r2_17
     * @todo   Implement testYy_r2_17().
     */
    public function testYy_r2_17() {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
                'This test has not been implemented yet.'
        );
    }

    /**
     * @covers Smarty_Internal_Templatelexer::yy_r2_18
     * @todo   Implement testYy_r2_18().
     */
    public function testYy_r2_18() {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
                'This test has not been implemented yet.'
        );
    }

    /**
     * @covers Smarty_Internal_Templatelexer::yy_r2_20
     * @todo   Implement testYy_r2_20().
     */
    public function testYy_r2_20() {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
                'This test has not been implemented yet.'
        );
    }

    /**
     * @covers Smarty_Internal_Templatelexer::yy_r2_22
     * @todo   Implement testYy_r2_22().
     */
    public function testYy_r2_22() {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
                'This test has not been implemented yet.'
        );
    }

    /**
     * @covers Smarty_Internal_Templatelexer::yy_r2_24
     * @todo   Implement testYy_r2_24().
     */
    public function testYy_r2_24() {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
                'This test has not been implemented yet.'
        );
    }

    /**
     * @covers Smarty_Internal_Templatelexer::yy_r2_26
     * @todo   Implement testYy_r2_26().
     */
    public function testYy_r2_26() {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
                'This test has not been implemented yet.'
        );
    }

    /**
     * @covers Smarty_Internal_Templatelexer::yy_r2_28
     * @todo   Implement testYy_r2_28().
     */
    public function testYy_r2_28() {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
                'This test has not been implemented yet.'
        );
    }

    /**
     * @covers Smarty_Internal_Templatelexer::yy_r2_30
     * @todo   Implement testYy_r2_30().
     */
    public function testYy_r2_30() {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
                'This test has not been implemented yet.'
        );
    }

    /**
     * @covers Smarty_Internal_Templatelexer::yy_r2_32
     * @todo   Implement testYy_r2_32().
     */
    public function testYy_r2_32() {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
                'This test has not been implemented yet.'
        );
    }

    /**
     * @covers Smarty_Internal_Templatelexer::yy_r2_34
     * @todo   Implement testYy_r2_34().
     */
    public function testYy_r2_34() {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
                'This test has not been implemented yet.'
        );
    }

    /**
     * @covers Smarty_Internal_Templatelexer::yy_r2_36
     * @todo   Implement testYy_r2_36().
     */
    public function testYy_r2_36() {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
                'This test has not been implemented yet.'
        );
    }

    /**
     * @covers Smarty_Internal_Templatelexer::yy_r2_38
     * @todo   Implement testYy_r2_38().
     */
    public function testYy_r2_38() {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
                'This test has not been implemented yet.'
        );
    }

    /**
     * @covers Smarty_Internal_Templatelexer::yy_r2_40
     * @todo   Implement testYy_r2_40().
     */
    public function testYy_r2_40() {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
                'This test has not been implemented yet.'
        );
    }

    /**
     * @covers Smarty_Internal_Templatelexer::yy_r2_41
     * @todo   Implement testYy_r2_41().
     */
    public function testYy_r2_41() {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
                'This test has not been implemented yet.'
        );
    }

    /**
     * @covers Smarty_Internal_Templatelexer::yy_r2_42
     * @todo   Implement testYy_r2_42().
     */
    public function testYy_r2_42() {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
                'This test has not been implemented yet.'
        );
    }

    /**
     * @covers Smarty_Internal_Templatelexer::yy_r2_43
     * @todo   Implement testYy_r2_43().
     */
    public function testYy_r2_43() {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
                'This test has not been implemented yet.'
        );
    }

    /**
     * @covers Smarty_Internal_Templatelexer::yy_r2_44
     * @todo   Implement testYy_r2_44().
     */
    public function testYy_r2_44() {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
                'This test has not been implemented yet.'
        );
    }

    /**
     * @covers Smarty_Internal_Templatelexer::yy_r2_45
     * @todo   Implement testYy_r2_45().
     */
    public function testYy_r2_45() {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
                'This test has not been implemented yet.'
        );
    }

    /**
     * @covers Smarty_Internal_Templatelexer::yy_r2_46
     * @todo   Implement testYy_r2_46().
     */
    public function testYy_r2_46() {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
                'This test has not been implemented yet.'
        );
    }

    /**
     * @covers Smarty_Internal_Templatelexer::yy_r2_47
     * @todo   Implement testYy_r2_47().
     */
    public function testYy_r2_47() {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
                'This test has not been implemented yet.'
        );
    }

    /**
     * @covers Smarty_Internal_Templatelexer::yy_r2_48
     * @todo   Implement testYy_r2_48().
     */
    public function testYy_r2_48() {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
                'This test has not been implemented yet.'
        );
    }

    /**
     * @covers Smarty_Internal_Templatelexer::yy_r2_49
     * @todo   Implement testYy_r2_49().
     */
    public function testYy_r2_49() {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
                'This test has not been implemented yet.'
        );
    }

    /**
     * @covers Smarty_Internal_Templatelexer::yy_r2_50
     * @todo   Implement testYy_r2_50().
     */
    public function testYy_r2_50() {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
                'This test has not been implemented yet.'
        );
    }

    /**
     * @covers Smarty_Internal_Templatelexer::yy_r2_54
     * @todo   Implement testYy_r2_54().
     */
    public function testYy_r2_54() {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
                'This test has not been implemented yet.'
        );
    }

    /**
     * @covers Smarty_Internal_Templatelexer::yy_r2_55
     * @todo   Implement testYy_r2_55().
     */
    public function testYy_r2_55() {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
                'This test has not been implemented yet.'
        );
    }

    /**
     * @covers Smarty_Internal_Templatelexer::yy_r2_56
     * @todo   Implement testYy_r2_56().
     */
    public function testYy_r2_56() {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
                'This test has not been implemented yet.'
        );
    }

    /**
     * @covers Smarty_Internal_Templatelexer::yy_r2_57
     * @todo   Implement testYy_r2_57().
     */
    public function testYy_r2_57() {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
                'This test has not been implemented yet.'
        );
    }

    /**
     * @covers Smarty_Internal_Templatelexer::yy_r2_58
     * @todo   Implement testYy_r2_58().
     */
    public function testYy_r2_58() {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
                'This test has not been implemented yet.'
        );
    }

    /**
     * @covers Smarty_Internal_Templatelexer::yy_r2_59
     * @todo   Implement testYy_r2_59().
     */
    public function testYy_r2_59() {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
                'This test has not been implemented yet.'
        );
    }

    /**
     * @covers Smarty_Internal_Templatelexer::yy_r2_60
     * @todo   Implement testYy_r2_60().
     */
    public function testYy_r2_60() {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
                'This test has not been implemented yet.'
        );
    }

    /**
     * @covers Smarty_Internal_Templatelexer::yy_r2_61
     * @todo   Implement testYy_r2_61().
     */
    public function testYy_r2_61() {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
                'This test has not been implemented yet.'
        );
    }

    /**
     * @covers Smarty_Internal_Templatelexer::yy_r2_63
     * @todo   Implement testYy_r2_63().
     */
    public function testYy_r2_63() {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
                'This test has not been implemented yet.'
        );
    }

    /**
     * @covers Smarty_Internal_Templatelexer::yy_r2_65
     * @todo   Implement testYy_r2_65().
     */
    public function testYy_r2_65() {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
                'This test has not been implemented yet.'
        );
    }

    /**
     * @covers Smarty_Internal_Templatelexer::yy_r2_67
     * @todo   Implement testYy_r2_67().
     */
    public function testYy_r2_67() {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
                'This test has not been implemented yet.'
        );
    }

    /**
     * @covers Smarty_Internal_Templatelexer::yy_r2_68
     * @todo   Implement testYy_r2_68().
     */
    public function testYy_r2_68() {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
                'This test has not been implemented yet.'
        );
    }

    /**
     * @covers Smarty_Internal_Templatelexer::yy_r2_69
     * @todo   Implement testYy_r2_69().
     */
    public function testYy_r2_69() {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
                'This test has not been implemented yet.'
        );
    }

    /**
     * @covers Smarty_Internal_Templatelexer::yy_r2_70
     * @todo   Implement testYy_r2_70().
     */
    public function testYy_r2_70() {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
                'This test has not been implemented yet.'
        );
    }

    /**
     * @covers Smarty_Internal_Templatelexer::yy_r2_71
     * @todo   Implement testYy_r2_71().
     */
    public function testYy_r2_71() {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
                'This test has not been implemented yet.'
        );
    }

    /**
     * @covers Smarty_Internal_Templatelexer::yy_r2_72
     * @todo   Implement testYy_r2_72().
     */
    public function testYy_r2_72() {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
                'This test has not been implemented yet.'
        );
    }

    /**
     * @covers Smarty_Internal_Templatelexer::yy_r2_73
     * @todo   Implement testYy_r2_73().
     */
    public function testYy_r2_73() {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
                'This test has not been implemented yet.'
        );
    }

    /**
     * @covers Smarty_Internal_Templatelexer::yy_r2_74
     * @todo   Implement testYy_r2_74().
     */
    public function testYy_r2_74() {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
                'This test has not been implemented yet.'
        );
    }

    /**
     * @covers Smarty_Internal_Templatelexer::yy_r2_75
     * @todo   Implement testYy_r2_75().
     */
    public function testYy_r2_75() {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
                'This test has not been implemented yet.'
        );
    }

    /**
     * @covers Smarty_Internal_Templatelexer::yy_r2_76
     * @todo   Implement testYy_r2_76().
     */
    public function testYy_r2_76() {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
                'This test has not been implemented yet.'
        );
    }

    /**
     * @covers Smarty_Internal_Templatelexer::yy_r2_77
     * @todo   Implement testYy_r2_77().
     */
    public function testYy_r2_77() {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
                'This test has not been implemented yet.'
        );
    }

    /**
     * @covers Smarty_Internal_Templatelexer::yy_r2_78
     * @todo   Implement testYy_r2_78().
     */
    public function testYy_r2_78() {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
                'This test has not been implemented yet.'
        );
    }

    /**
     * @covers Smarty_Internal_Templatelexer::yy_r2_79
     * @todo   Implement testYy_r2_79().
     */
    public function testYy_r2_79() {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
                'This test has not been implemented yet.'
        );
    }

    /**
     * @covers Smarty_Internal_Templatelexer::yy_r2_80
     * @todo   Implement testYy_r2_80().
     */
    public function testYy_r2_80() {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
                'This test has not been implemented yet.'
        );
    }

    /**
     * @covers Smarty_Internal_Templatelexer::yy_r2_82
     * @todo   Implement testYy_r2_82().
     */
    public function testYy_r2_82() {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
                'This test has not been implemented yet.'
        );
    }

    /**
     * @covers Smarty_Internal_Templatelexer::yy_r2_83
     * @todo   Implement testYy_r2_83().
     */
    public function testYy_r2_83() {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
                'This test has not been implemented yet.'
        );
    }

    /**
     * @covers Smarty_Internal_Templatelexer::yy_r2_84
     * @todo   Implement testYy_r2_84().
     */
    public function testYy_r2_84() {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
                'This test has not been implemented yet.'
        );
    }

    /**
     * @covers Smarty_Internal_Templatelexer::yy_r2_85
     * @todo   Implement testYy_r2_85().
     */
    public function testYy_r2_85() {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
                'This test has not been implemented yet.'
        );
    }

    /**
     * @covers Smarty_Internal_Templatelexer::yy_r2_86
     * @todo   Implement testYy_r2_86().
     */
    public function testYy_r2_86() {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
                'This test has not been implemented yet.'
        );
    }

    /**
     * @covers Smarty_Internal_Templatelexer::yy_r2_87
     * @todo   Implement testYy_r2_87().
     */
    public function testYy_r2_87() {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
                'This test has not been implemented yet.'
        );
    }

    /**
     * @covers Smarty_Internal_Templatelexer::yylex3
     * @todo   Implement testYylex3().
     */
    public function testYylex3() {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
                'This test has not been implemented yet.'
        );
    }

    /**
     * @covers Smarty_Internal_Templatelexer::yy_r3_1
     * @todo   Implement testYy_r3_1().
     */
    public function testYy_r3_1() {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
                'This test has not been implemented yet.'
        );
    }

    /**
     * @covers Smarty_Internal_Templatelexer::yy_r3_2
     * @todo   Implement testYy_r3_2().
     */
    public function testYy_r3_2() {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
                'This test has not been implemented yet.'
        );
    }

    /**
     * @covers Smarty_Internal_Templatelexer::yy_r3_3
     * @todo   Implement testYy_r3_3().
     */
    public function testYy_r3_3() {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
                'This test has not been implemented yet.'
        );
    }

    /**
     * @covers Smarty_Internal_Templatelexer::yy_r3_4
     * @todo   Implement testYy_r3_4().
     */
    public function testYy_r3_4() {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
                'This test has not been implemented yet.'
        );
    }

    /**
     * @covers Smarty_Internal_Templatelexer::yy_r3_5
     * @todo   Implement testYy_r3_5().
     */
    public function testYy_r3_5() {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
                'This test has not been implemented yet.'
        );
    }

    /**
     * @covers Smarty_Internal_Templatelexer::yy_r3_8
     * @todo   Implement testYy_r3_8().
     */
    public function testYy_r3_8() {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
                'This test has not been implemented yet.'
        );
    }

    /**
     * @covers Smarty_Internal_Templatelexer::yylex4
     * @todo   Implement testYylex4().
     */
    public function testYylex4() {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
                'This test has not been implemented yet.'
        );
    }

    /**
     * @covers Smarty_Internal_Templatelexer::yy_r4_1
     * @todo   Implement testYy_r4_1().
     */
    public function testYy_r4_1() {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
                'This test has not been implemented yet.'
        );
    }

    /**
     * @covers Smarty_Internal_Templatelexer::yy_r4_2
     * @todo   Implement testYy_r4_2().
     */
    public function testYy_r4_2() {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
                'This test has not been implemented yet.'
        );
    }

    /**
     * @covers Smarty_Internal_Templatelexer::yy_r4_3
     * @todo   Implement testYy_r4_3().
     */
    public function testYy_r4_3() {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
                'This test has not been implemented yet.'
        );
    }

    /**
     * @covers Smarty_Internal_Templatelexer::yy_r4_4
     * @todo   Implement testYy_r4_4().
     */
    public function testYy_r4_4() {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
                'This test has not been implemented yet.'
        );
    }

    /**
     * @covers Smarty_Internal_Templatelexer::yy_r4_5
     * @todo   Implement testYy_r4_5().
     */
    public function testYy_r4_5() {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
                'This test has not been implemented yet.'
        );
    }

    /**
     * @covers Smarty_Internal_Templatelexer::yy_r4_6
     * @todo   Implement testYy_r4_6().
     */
    public function testYy_r4_6() {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
                'This test has not been implemented yet.'
        );
    }

    /**
     * @covers Smarty_Internal_Templatelexer::yy_r4_7
     * @todo   Implement testYy_r4_7().
     */
    public function testYy_r4_7() {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
                'This test has not been implemented yet.'
        );
    }

    /**
     * @covers Smarty_Internal_Templatelexer::yy_r4_8
     * @todo   Implement testYy_r4_8().
     */
    public function testYy_r4_8() {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
                'This test has not been implemented yet.'
        );
    }

    /**
     * @covers Smarty_Internal_Templatelexer::yy_r4_9
     * @todo   Implement testYy_r4_9().
     */
    public function testYy_r4_9() {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
                'This test has not been implemented yet.'
        );
    }

    /**
     * @covers Smarty_Internal_Templatelexer::yy_r4_13
     * @todo   Implement testYy_r4_13().
     */
    public function testYy_r4_13() {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
                'This test has not been implemented yet.'
        );
    }

}
