<?php

/**
 * Generated by PHPUnit_SkeletonGenerator 1.2.1 on 2014-08-09 at 08:17:37.
 */
class Smarty_Internal_Security_HandlerTest extends PHPUnit_Framework_TestCase {

    /**
     * @var Smarty_Internal_Security_Handler
     */
    protected $object;

    /**
     * Sets up the fixture, for example, opens a network connection.
     * This method is called before a test is executed.
     */
    protected function setUp() {
        $this->object = new Smarty_Internal_Security_Handler;
    }

    /**
     * Tears down the fixture, for example, closes a network connection.
     * This method is called after a test is executed.
     */
    protected function tearDown() {
        
    }

    /**
     * @covers Smarty_Internal_Security_Handler::isTrustedPhpFunction
     * @todo   Implement testIsTrustedPhpFunction().
     */
    public function testIsTrustedPhpFunction() {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
                'This test has not been implemented yet.'
        );
    }

    /**
     * @covers Smarty_Internal_Security_Handler::isTrustedStaticClass
     * @todo   Implement testIsTrustedStaticClass().
     */
    public function testIsTrustedStaticClass() {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
                'This test has not been implemented yet.'
        );
    }

    /**
     * @covers Smarty_Internal_Security_Handler::isTrustedModifier
     * @todo   Implement testIsTrustedModifier().
     */
    public function testIsTrustedModifier() {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
                'This test has not been implemented yet.'
        );
    }

    /**
     * @covers Smarty_Internal_Security_Handler::isTrustedStream
     * @todo   Implement testIsTrustedStream().
     */
    public function testIsTrustedStream() {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
                'This test has not been implemented yet.'
        );
    }

    /**
     * @covers Smarty_Internal_Security_Handler::isTrustedResourceDir
     * @todo   Implement testIsTrustedResourceDir().
     */
    public function testIsTrustedResourceDir() {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
                'This test has not been implemented yet.'
        );
    }

    /**
     * @covers Smarty_Internal_Security_Handler::isTrustedPHPDir
     * @todo   Implement testIsTrustedPHPDir().
     */
    public function testIsTrustedPHPDir() {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
                'This test has not been implemented yet.'
        );
    }

}
