<?php

/**
 * Generated by PHPUnit_SkeletonGenerator 1.2.1 on 2014-08-09 at 08:17:23.
 */
class Smarty_Internal_Write_FileTest extends PHPUnit_Framework_TestCase {

    /**
     * @var Smarty_Internal_Write_File
     */
    protected $object;

    /**
     * Sets up the fixture, for example, opens a network connection.
     * This method is called before a test is executed.
     */
    protected function setUp() {
        $this->object = new Smarty_Internal_Write_File;
    }

    /**
     * Tears down the fixture, for example, closes a network connection.
     * This method is called after a test is executed.
     */
    protected function tearDown() {
        
    }

    /**
     * @covers Smarty_Internal_Write_File::writeFile
     * @todo   Implement testWriteFile().
     */
    public function testWriteFile() {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
                'This test has not been implemented yet.'
        );
    }

}
