<?php

/**
 * Generated by PHPUnit_SkeletonGenerator 1.2.1 on 2014-08-09 at 08:17:50.
 */
class Smarty_Internal_CompileBaseTest extends PHPUnit_Framework_TestCase {

    /**
     * @var Smarty_Internal_CompileBase
     */
    protected $object;

    /**
     * Sets up the fixture, for example, opens a network connection.
     * This method is called before a test is executed.
     */
    protected function setUp() {
        $this->object = new Smarty_Internal_CompileBase;
    }

    /**
     * Tears down the fixture, for example, closes a network connection.
     * This method is called after a test is executed.
     */
    protected function tearDown() {
        
    }

    /**
     * @covers Smarty_Internal_CompileBase::_get_attributes
     * @todo   Implement test_get_attributes().
     */
    public function test_get_attributes() {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
                'This test has not been implemented yet.'
        );
    }

    /**
     * @covers Smarty_Internal_CompileBase::_open_tag
     * @todo   Implement test_open_tag().
     */
    public function test_open_tag() {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
                'This test has not been implemented yet.'
        );
    }

    /**
     * @covers Smarty_Internal_CompileBase::_close_tag
     * @todo   Implement test_close_tag().
     */
    public function test_close_tag() {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
                'This test has not been implemented yet.'
        );
    }

}
