<?php

/**
 * Generated by PHPUnit_SkeletonGenerator 1.2.1 on 2014-08-09 at 08:17:22.
 */
class Smarty_Internal_Resource_PHPTest extends PHPUnit_Framework_TestCase {

    /**
     * @var Smarty_Internal_Resource_PHP
     */
    protected $object;

    /**
     * Sets up the fixture, for example, opens a network connection.
     * This method is called before a test is executed.
     */
    protected function setUp() {
        $this->object = new Smarty_Internal_Resource_PHP;
    }

    /**
     * Tears down the fixture, for example, closes a network connection.
     * This method is called after a test is executed.
     */
    protected function tearDown() {
        
    }

    /**
     * @covers Smarty_Internal_Resource_PHP::isExisting
     * @todo   Implement testIsExisting().
     */
    public function testIsExisting() {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
                'This test has not been implemented yet.'
        );
    }

    /**
     * @covers Smarty_Internal_Resource_PHP::getTemplateFilepath
     * @todo   Implement testGetTemplateFilepath().
     */
    public function testGetTemplateFilepath() {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
                'This test has not been implemented yet.'
        );
    }

    /**
     * @covers Smarty_Internal_Resource_PHP::getTemplateTimestamp
     * @todo   Implement testGetTemplateTimestamp().
     */
    public function testGetTemplateTimestamp() {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
                'This test has not been implemented yet.'
        );
    }

    /**
     * @covers Smarty_Internal_Resource_PHP::getTemplateSource
     * @todo   Implement testGetTemplateSource().
     */
    public function testGetTemplateSource() {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
                'This test has not been implemented yet.'
        );
    }

    /**
     * @covers Smarty_Internal_Resource_PHP::getCompiledFilepath
     * @todo   Implement testGetCompiledFilepath().
     */
    public function testGetCompiledFilepath() {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
                'This test has not been implemented yet.'
        );
    }

    /**
     * @covers Smarty_Internal_Resource_PHP::renderUncompiled
     * @todo   Implement testRenderUncompiled().
     */
    public function testRenderUncompiled() {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
                'This test has not been implemented yet.'
        );
    }

}
