<?php

/**
 * Generated by PHPUnit_SkeletonGenerator 1.2.1 on 2014-08-09 at 08:17:18.
 */
class Smarty_Internal_ConfigTest extends PHPUnit_Framework_TestCase {

    /**
     * @var Smarty_Internal_Config
     */
    protected $object;

    /**
     * Sets up the fixture, for example, opens a network connection.
     * This method is called before a test is executed.
     */
    protected function setUp() {
        $this->object = new Smarty_Internal_Config;
    }

    /**
     * Tears down the fixture, for example, closes a network connection.
     * This method is called after a test is executed.
     */
    protected function tearDown() {
        
    }

    /**
     * @covers Smarty_Internal_Config::getConfigFilepath
     * @todo   Implement testGetConfigFilepath().
     */
    public function testGetConfigFilepath() {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
                'This test has not been implemented yet.'
        );
    }

    /**
     * @covers Smarty_Internal_Config::getTimestamp
     * @todo   Implement testGetTimestamp().
     */
    public function testGetTimestamp() {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
                'This test has not been implemented yet.'
        );
    }

    /**
     * @covers Smarty_Internal_Config::buildConfigFilepath
     * @todo   Implement testBuildConfigFilepath().
     */
    public function testBuildConfigFilepath() {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
                'This test has not been implemented yet.'
        );
    }

    /**
     * @covers Smarty_Internal_Config::getConfigSource
     * @todo   Implement testGetConfigSource().
     */
    public function testGetConfigSource() {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
                'This test has not been implemented yet.'
        );
    }

    /**
     * @covers Smarty_Internal_Config::readConfigSource
     * @todo   Implement testReadConfigSource().
     */
    public function testReadConfigSource() {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
                'This test has not been implemented yet.'
        );
    }

    /**
     * @covers Smarty_Internal_Config::getCompiledFilepath
     * @todo   Implement testGetCompiledFilepath().
     */
    public function testGetCompiledFilepath() {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
                'This test has not been implemented yet.'
        );
    }

    /**
     * @covers Smarty_Internal_Config::buildCompiledFilepath
     * @todo   Implement testBuildCompiledFilepath().
     */
    public function testBuildCompiledFilepath() {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
                'This test has not been implemented yet.'
        );
    }

    /**
     * @covers Smarty_Internal_Config::getCompiledTimestamp
     * @todo   Implement testGetCompiledTimestamp().
     */
    public function testGetCompiledTimestamp() {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
                'This test has not been implemented yet.'
        );
    }

    /**
     * @covers Smarty_Internal_Config::mustCompile
     * @todo   Implement testMustCompile().
     */
    public function testMustCompile() {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
                'This test has not been implemented yet.'
        );
    }

    /**
     * @covers Smarty_Internal_Config::getCompiledConfig
     * @todo   Implement testGetCompiledConfig().
     */
    public function testGetCompiledConfig() {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
                'This test has not been implemented yet.'
        );
    }

    /**
     * @covers Smarty_Internal_Config::compileConfigSource
     * @todo   Implement testCompileConfigSource().
     */
    public function testCompileConfigSource() {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
                'This test has not been implemented yet.'
        );
    }

    /**
     * @covers Smarty_Internal_Config::loadConfigVars
     * @todo   Implement testLoadConfigVars().
     */
    public function testLoadConfigVars() {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
                'This test has not been implemented yet.'
        );
    }

}
