<?php

/**
 * Generated by PHPUnit_SkeletonGenerator 1.2.1 on 2014-08-09 at 08:17:02.
 */
class Smarty_Internal_TemplateCompilerBaseTest extends PHPUnit_Framework_TestCase {

    /**
     * @var Smarty_Internal_TemplateCompilerBase
     */
    protected $object;

    /**
     * Sets up the fixture, for example, opens a network connection.
     * This method is called before a test is executed.
     */
    protected function setUp() {
        $this->object = new Smarty_Internal_TemplateCompilerBase;
    }

    /**
     * Tears down the fixture, for example, closes a network connection.
     * This method is called after a test is executed.
     */
    protected function tearDown() {
        
    }

    /**
     * @covers Smarty_Internal_TemplateCompilerBase::compileTemplate
     * @todo   Implement testCompileTemplate().
     */
    public function testCompileTemplate() {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
                'This test has not been implemented yet.'
        );
    }

    /**
     * @covers Smarty_Internal_TemplateCompilerBase::compileTag
     * @todo   Implement testCompileTag().
     */
    public function testCompileTag() {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
                'This test has not been implemented yet.'
        );
    }

    /**
     * @covers Smarty_Internal_TemplateCompilerBase::callTagCompiler
     * @todo   Implement testCallTagCompiler().
     */
    public function testCallTagCompiler() {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
                'This test has not been implemented yet.'
        );
    }

    /**
     * @covers Smarty_Internal_TemplateCompilerBase::getPlugin
     * @todo   Implement testGetPlugin().
     */
    public function testGetPlugin() {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
                'This test has not been implemented yet.'
        );
    }

    /**
     * @covers Smarty_Internal_TemplateCompilerBase::processNocacheCode
     * @todo   Implement testProcessNocacheCode().
     */
    public function testProcessNocacheCode() {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
                'This test has not been implemented yet.'
        );
    }

    /**
     * @covers Smarty_Internal_TemplateCompilerBase::trigger_template_error
     * @todo   Implement testTrigger_template_error().
     */
    public function testTrigger_template_error() {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
                'This test has not been implemented yet.'
        );
    }

}
