<?php

/**
 * Generated by PHPUnit_SkeletonGenerator 1.2.1 on 2014-08-09 at 08:17:01.
 */
class Smarty_Internal_CacheResource_FileTest extends PHPUnit_Framework_TestCase {

    /**
     * @var Smarty_Internal_CacheResource_File
     */
    protected $object;

    /**
     * Sets up the fixture, for example, opens a network connection.
     * This method is called before a test is executed.
     */
    protected function setUp() {
        $this->object = new Smarty_Internal_CacheResource_File;
    }

    /**
     * Tears down the fixture, for example, closes a network connection.
     * This method is called after a test is executed.
     */
    protected function tearDown() {
        
    }

    /**
     * @covers Smarty_Internal_CacheResource_File::getCachedFilepath
     * @todo   Implement testGetCachedFilepath().
     */
    public function testGetCachedFilepath() {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
                'This test has not been implemented yet.'
        );
    }

    /**
     * @covers Smarty_Internal_CacheResource_File::getCachedTimestamp
     * @todo   Implement testGetCachedTimestamp().
     */
    public function testGetCachedTimestamp() {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
                'This test has not been implemented yet.'
        );
    }

    /**
     * @covers Smarty_Internal_CacheResource_File::getCachedContents
     * @todo   Implement testGetCachedContents().
     */
    public function testGetCachedContents() {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
                'This test has not been implemented yet.'
        );
    }

    /**
     * @covers Smarty_Internal_CacheResource_File::writeCachedContent
     * @todo   Implement testWriteCachedContent().
     */
    public function testWriteCachedContent() {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
                'This test has not been implemented yet.'
        );
    }

    /**
     * @covers Smarty_Internal_CacheResource_File::clearAll
     * @todo   Implement testClearAll().
     */
    public function testClearAll() {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
                'This test has not been implemented yet.'
        );
    }

    /**
     * @covers Smarty_Internal_CacheResource_File::clear
     * @todo   Implement testClear().
     */
    public function testClear() {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
                'This test has not been implemented yet.'
        );
    }

}
