<?php

/**
 * Generated by PHPUnit_SkeletonGenerator 1.2.1 on 2014-08-09 at 08:17:52.
 */
class Config_FileTest extends PHPUnit_Framework_TestCase {

    /**
     * @var Config_File
     */
    protected $object;

    /**
     * Sets up the fixture, for example, opens a network connection.
     * This method is called before a test is executed.
     */
    protected function setUp() {
        $this->object = new Config_File;
    }

    /**
     * Tears down the fixture, for example, closes a network connection.
     * This method is called after a test is executed.
     */
    protected function tearDown() {
        
    }

    /**
     * @covers Config_File::set_path
     * @todo   Implement testSet_path().
     */
    public function testSet_path() {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
                'This test has not been implemented yet.'
        );
    }

    /**
     * @covers Config_File::get
     * @todo   Implement testGet().
     */
    public function testGet() {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
                'This test has not been implemented yet.'
        );
    }

    /**
     * @covers Config_File::get_key
     * @todo   Implement testGet_key().
     */
    public function testGet_key() {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
                'This test has not been implemented yet.'
        );
    }

    /**
     * @covers Config_File::get_file_names
     * @todo   Implement testGet_file_names().
     */
    public function testGet_file_names() {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
                'This test has not been implemented yet.'
        );
    }

    /**
     * @covers Config_File::get_section_names
     * @todo   Implement testGet_section_names().
     */
    public function testGet_section_names() {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
                'This test has not been implemented yet.'
        );
    }

    /**
     * @covers Config_File::get_var_names
     * @todo   Implement testGet_var_names().
     */
    public function testGet_var_names() {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
                'This test has not been implemented yet.'
        );
    }

    /**
     * @covers Config_File::clear
     * @todo   Implement testClear().
     */
    public function testClear() {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
                'This test has not been implemented yet.'
        );
    }

    /**
     * @covers Config_File::load_file
     * @todo   Implement testLoad_file().
     */
    public function testLoad_file() {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
                'This test has not been implemented yet.'
        );
    }

    /**
     * @covers Config_File::set_file_contents
     * @todo   Implement testSet_file_contents().
     */
    public function testSet_file_contents() {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
                'This test has not been implemented yet.'
        );
    }

    /**
     * @covers Config_File::parse_contents
     * @todo   Implement testParse_contents().
     */
    public function testParse_contents() {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
                'This test has not been implemented yet.'
        );
    }

    /**
     * @covers Config_File::_set_config_var
     * @todo   Implement test_set_config_var().
     */
    public function test_set_config_var() {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
                'This test has not been implemented yet.'
        );
    }

    /**
     * @covers Config_File::_trigger_error_msg
     * @todo   Implement test_trigger_error_msg().
     */
    public function test_trigger_error_msg() {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
                'This test has not been implemented yet.'
        );
    }

}
