<?php

/**
 * Generated by PHPUnit_SkeletonGenerator 1.2.1 on 2014-08-09 at 08:18:47.
 */
class XML_SerializerTest extends PHPUnit_Framework_TestCase {

    /**
     * @var XML_Serializer
     */
    protected $object;

    /**
     * Sets up the fixture, for example, opens a network connection.
     * This method is called before a test is executed.
     */
    protected function setUp() {
        $this->object = new XML_Serializer;
    }

    /**
     * Tears down the fixture, for example, closes a network connection.
     * This method is called after a test is executed.
     */
    protected function tearDown() {
        
    }

    /**
     * @covers XML_Serializer::apiVersion
     * @todo   Implement testApiVersion().
     */
    public function testApiVersion() {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
                'This test has not been implemented yet.'
        );
    }

    /**
     * @covers XML_Serializer::resetOptions
     * @todo   Implement testResetOptions().
     */
    public function testResetOptions() {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
                'This test has not been implemented yet.'
        );
    }

    /**
     * @covers XML_Serializer::setOption
     * @todo   Implement testSetOption().
     */
    public function testSetOption() {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
                'This test has not been implemented yet.'
        );
    }

    /**
     * @covers XML_Serializer::setOptions
     * @todo   Implement testSetOptions().
     */
    public function testSetOptions() {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
                'This test has not been implemented yet.'
        );
    }

    /**
     * @covers XML_Serializer::serialize
     * @todo   Implement testSerialize().
     */
    public function testSerialize() {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
                'This test has not been implemented yet.'
        );
    }

    /**
     * @covers XML_Serializer::getSerializedData
     * @todo   Implement testGetSerializedData().
     */
    public function testGetSerializedData() {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
                'This test has not been implemented yet.'
        );
    }

    /**
     * @covers XML_Serializer::_serializeValue
     * @todo   Implement test_serializeValue().
     */
    public function test_serializeValue() {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
                'This test has not been implemented yet.'
        );
    }

    /**
     * @covers XML_Serializer::_serializeArray
     * @todo   Implement test_serializeArray().
     */
    public function test_serializeArray() {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
                'This test has not been implemented yet.'
        );
    }

    /**
     * @covers XML_Serializer::_getDefaultTagname
     * @todo   Implement test_getDefaultTagname().
     */
    public function test_getDefaultTagname() {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
                'This test has not been implemented yet.'
        );
    }

    /**
     * @covers XML_Serializer::_serializeObject
     * @todo   Implement test_serializeObject().
     */
    public function test_serializeObject() {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
                'This test has not been implemented yet.'
        );
    }

    /**
     * @covers XML_Serializer::_createXMLTag
     * @todo   Implement test_createXMLTag().
     */
    public function test_createXMLTag() {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
                'This test has not been implemented yet.'
        );
    }

}
