<?php

/**
 * Generated by PHPUnit_SkeletonGenerator 1.2.1 on 2014-08-09 at 08:18:46.
 */
class XML_UnserializerTest extends PHPUnit_Framework_TestCase {

    /**
     * @var XML_Unserializer
     */
    protected $object;

    /**
     * Sets up the fixture, for example, opens a network connection.
     * This method is called before a test is executed.
     */
    protected function setUp() {
        $this->object = new XML_Unserializer;
    }

    /**
     * Tears down the fixture, for example, closes a network connection.
     * This method is called after a test is executed.
     */
    protected function tearDown() {
        
    }

    /**
     * @covers XML_Unserializer::apiVersion
     * @todo   Implement testApiVersion().
     */
    public function testApiVersion() {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
                'This test has not been implemented yet.'
        );
    }

    /**
     * @covers XML_Unserializer::resetOptions
     * @todo   Implement testResetOptions().
     */
    public function testResetOptions() {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
                'This test has not been implemented yet.'
        );
    }

    /**
     * @covers XML_Unserializer::setOption
     * @todo   Implement testSetOption().
     */
    public function testSetOption() {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
                'This test has not been implemented yet.'
        );
    }

    /**
     * @covers XML_Unserializer::setOptions
     * @todo   Implement testSetOptions().
     */
    public function testSetOptions() {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
                'This test has not been implemented yet.'
        );
    }

    /**
     * @covers XML_Unserializer::unserialize
     * @todo   Implement testUnserialize().
     */
    public function testUnserialize() {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
                'This test has not been implemented yet.'
        );
    }

    /**
     * @covers XML_Unserializer::getUnserializedData
     * @todo   Implement testGetUnserializedData().
     */
    public function testGetUnserializedData() {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
                'This test has not been implemented yet.'
        );
    }

    /**
     * @covers XML_Unserializer::getRootName
     * @todo   Implement testGetRootName().
     */
    public function testGetRootName() {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
                'This test has not been implemented yet.'
        );
    }

    /**
     * @covers XML_Unserializer::startHandler
     * @todo   Implement testStartHandler().
     */
    public function testStartHandler() {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
                'This test has not been implemented yet.'
        );
    }

    /**
     * @covers XML_Unserializer::_guessAndSetTypes
     * @todo   Implement test_guessAndSetTypes().
     */
    public function test_guessAndSetTypes() {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
                'This test has not been implemented yet.'
        );
    }

    /**
     * @covers XML_Unserializer::_guessAndSetType
     * @todo   Implement test_guessAndSetType().
     */
    public function test_guessAndSetType() {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
                'This test has not been implemented yet.'
        );
    }

    /**
     * @covers XML_Unserializer::endHandler
     * @todo   Implement testEndHandler().
     */
    public function testEndHandler() {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
                'This test has not been implemented yet.'
        );
    }

    /**
     * @covers XML_Unserializer::cdataHandler
     * @todo   Implement testCdataHandler().
     */
    public function testCdataHandler() {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
                'This test has not been implemented yet.'
        );
    }

    /**
     * @covers XML_Unserializer::_getComplexType
     * @todo   Implement test_getComplexType().
     */
    public function test_getComplexType() {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
                'This test has not been implemented yet.'
        );
    }

    /**
     * @covers XML_Unserializer::_createParser
     * @todo   Implement test_createParser().
     */
    public function test_createParser() {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
                'This test has not been implemented yet.'
        );
    }

}
