<?php

/**
 * Generated by PHPUnit_SkeletonGenerator 1.2.1 on 2014-08-09 at 08:18:48.
 */
class XML_UtilTest extends PHPUnit_Framework_TestCase {

    /**
     * @var XML_Util
     */
    protected $object;

    /**
     * Sets up the fixture, for example, opens a network connection.
     * This method is called before a test is executed.
     */
    protected function setUp() {
        $this->object = new XML_Util;
    }

    /**
     * Tears down the fixture, for example, closes a network connection.
     * This method is called after a test is executed.
     */
    protected function tearDown() {
        
    }

    /**
     * @covers XML_Util::apiVersion
     * @todo   Implement testApiVersion().
     */
    public function testApiVersion() {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
                'This test has not been implemented yet.'
        );
    }

    /**
     * @covers XML_Util::replaceEntities
     * @todo   Implement testReplaceEntities().
     */
    public function testReplaceEntities() {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
                'This test has not been implemented yet.'
        );
    }

    /**
     * @covers XML_Util::reverseEntities
     * @todo   Implement testReverseEntities().
     */
    public function testReverseEntities() {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
                'This test has not been implemented yet.'
        );
    }

    /**
     * @covers XML_Util::getXMLDeclaration
     * @todo   Implement testGetXMLDeclaration().
     */
    public function testGetXMLDeclaration() {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
                'This test has not been implemented yet.'
        );
    }

    /**
     * @covers XML_Util::getDocTypeDeclaration
     * @todo   Implement testGetDocTypeDeclaration().
     */
    public function testGetDocTypeDeclaration() {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
                'This test has not been implemented yet.'
        );
    }

    /**
     * @covers XML_Util::attributesToString
     * @todo   Implement testAttributesToString().
     */
    public function testAttributesToString() {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
                'This test has not been implemented yet.'
        );
    }

    /**
     * @covers XML_Util::collapseEmptyTags
     * @todo   Implement testCollapseEmptyTags().
     */
    public function testCollapseEmptyTags() {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
                'This test has not been implemented yet.'
        );
    }

    /**
     * @covers XML_Util::createTag
     * @todo   Implement testCreateTag().
     */
    public function testCreateTag() {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
                'This test has not been implemented yet.'
        );
    }

    /**
     * @covers XML_Util::createTagFromArray
     * @todo   Implement testCreateTagFromArray().
     */
    public function testCreateTagFromArray() {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
                'This test has not been implemented yet.'
        );
    }

    /**
     * @covers XML_Util::createStartElement
     * @todo   Implement testCreateStartElement().
     */
    public function testCreateStartElement() {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
                'This test has not been implemented yet.'
        );
    }

    /**
     * @covers XML_Util::createEndElement
     * @todo   Implement testCreateEndElement().
     */
    public function testCreateEndElement() {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
                'This test has not been implemented yet.'
        );
    }

    /**
     * @covers XML_Util::createComment
     * @todo   Implement testCreateComment().
     */
    public function testCreateComment() {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
                'This test has not been implemented yet.'
        );
    }

    /**
     * @covers XML_Util::createCDataSection
     * @todo   Implement testCreateCDataSection().
     */
    public function testCreateCDataSection() {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
                'This test has not been implemented yet.'
        );
    }

    /**
     * @covers XML_Util::splitQualifiedName
     * @todo   Implement testSplitQualifiedName().
     */
    public function testSplitQualifiedName() {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
                'This test has not been implemented yet.'
        );
    }

    /**
     * @covers XML_Util::isValidName
     * @todo   Implement testIsValidName().
     */
    public function testIsValidName() {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
                'This test has not been implemented yet.'
        );
    }

    /**
     * @covers XML_Util::raiseError
     * @todo   Implement testRaiseError().
     */
    public function testRaiseError() {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
                'This test has not been implemented yet.'
        );
    }

}
