<?php

/**
 * Generated by PHPUnit_SkeletonGenerator 1.2.1 on 2014-08-09 at 08:18:18.
 */
class PHPUnit_GUI_GtkTest extends PHPUnit_Framework_TestCase {

    /**
     * @var PHPUnit_GUI_Gtk
     */
    protected $object;

    /**
     * Sets up the fixture, for example, opens a network connection.
     * This method is called before a test is executed.
     */
    protected function setUp() {
        $this->object = new PHPUnit_GUI_Gtk;
    }

    /**
     * Tears down the fixture, for example, closes a network connection.
     * This method is called after a test is executed.
     */
    protected function tearDown() {
        
    }

    /**
     * @covers PHPUnit_GUI_Gtk::main
     * @todo   Implement testMain().
     */
    public function testMain() {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
                'This test has not been implemented yet.'
        );
    }

    /**
     * @covers PHPUnit_GUI_Gtk::_createUI
     * @todo   Implement test_createUI().
     */
    public function test_createUI() {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
                'This test has not been implemented yet.'
        );
    }

    /**
     * @covers PHPUnit_GUI_Gtk::_createMenu
     * @todo   Implement test_createMenu().
     */
    public function test_createMenu() {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
                'This test has not been implemented yet.'
        );
    }

    /**
     * @covers PHPUnit_GUI_Gtk::_createSuiteEntry
     * @todo   Implement test_createSuiteEntry().
     */
    public function test_createSuiteEntry() {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
                'This test has not been implemented yet.'
        );
    }

    /**
     * @covers PHPUnit_GUI_Gtk::_createReportLabels
     * @todo   Implement test_createReportLabels().
     */
    public function test_createReportLabels() {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
                'This test has not been implemented yet.'
        );
    }

    /**
     * @covers PHPUnit_GUI_Gtk::_createProgressBar
     * @todo   Implement test_createProgressBar().
     */
    public function test_createProgressBar() {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
                'This test has not been implemented yet.'
        );
    }

    /**
     * @covers PHPUnit_GUI_Gtk::_createReportAreas
     * @todo   Implement test_createReportAreas().
     */
    public function test_createReportAreas() {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
                'This test has not been implemented yet.'
        );
    }

    /**
     * @covers PHPUnit_GUI_Gtk::_createStatusLine
     * @todo   Implement test_createStatusLine().
     */
    public function test_createStatusLine() {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
                'This test has not been implemented yet.'
        );
    }

    /**
     * @covers PHPUnit_GUI_Gtk::about
     * @todo   Implement testAbout().
     */
    public function testAbout() {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
                'This test has not been implemented yet.'
        );
    }

    /**
     * @covers PHPUnit_GUI_Gtk::loadTest
     * @todo   Implement testLoadTest().
     */
    public function testLoadTest() {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
                'This test has not been implemented yet.'
        );
    }

    /**
     * @covers PHPUnit_GUI_Gtk::runTest
     * @todo   Implement testRunTest().
     */
    public function testRunTest() {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
                'This test has not been implemented yet.'
        );
    }

    /**
     * @covers PHPUnit_GUI_Gtk::_setLabelValue
     * @todo   Implement test_setLabelValue().
     */
    public function test_setLabelValue() {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
                'This test has not been implemented yet.'
        );
    }

    /**
     * @covers PHPUnit_GUI_Gtk::run
     * @todo   Implement testRun().
     */
    public function testRun() {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
                'This test has not been implemented yet.'
        );
    }

    /**
     * @covers PHPUnit_GUI_Gtk::_showStatus
     * @todo   Implement test_showStatus().
     */
    public function test_showStatus() {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
                'This test has not been implemented yet.'
        );
    }

    /**
     * @covers PHPUnit_GUI_Gtk::show
     * @todo   Implement testShow().
     */
    public function testShow() {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
                'This test has not been implemented yet.'
        );
    }

    /**
     * @covers PHPUnit_GUI_Gtk::addSuites
     * @todo   Implement testAddSuites().
     */
    public function testAddSuites() {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
                'This test has not been implemented yet.'
        );
    }

    /**
     * @covers PHPUnit_GUI_Gtk::_showAll
     * @todo   Implement test_showAll().
     */
    public function test_showAll() {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
                'This test has not been implemented yet.'
        );
    }

    /**
     * @covers PHPUnit_GUI_Gtk::_showFailures
     * @todo   Implement test_showFailures().
     */
    public function test_showFailures() {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
                'This test has not been implemented yet.'
        );
    }

    /**
     * @covers PHPUnit_GUI_Gtk::_updateProgress
     * @todo   Implement test_updateProgress().
     */
    public function test_updateProgress() {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
                'This test has not been implemented yet.'
        );
    }

}
