<?php

/**
 * Generated by PHPUnit_SkeletonGenerator 1.2.1 on 2014-08-09 at 08:18:19.
 */
class PHPUnit_GUI_HTMLTest extends PHPUnit_Framework_TestCase {

    /**
     * @var PHPUnit_GUI_HTML
     */
    protected $object;

    /**
     * Sets up the fixture, for example, opens a network connection.
     * This method is called before a test is executed.
     */
    protected function setUp() {
        $this->object = new PHPUnit_GUI_HTML;
    }

    /**
     * Tears down the fixture, for example, closes a network connection.
     * This method is called after a test is executed.
     */
    protected function tearDown() {
        
    }

    /**
     * @covers PHPUnit_GUI_HTML::addSuites
     * @todo   Implement testAddSuites().
     */
    public function testAddSuites() {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
                'This test has not been implemented yet.'
        );
    }

    /**
     * @covers PHPUnit_GUI_HTML::show
     * @todo   Implement testShow().
     */
    public function testShow() {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
                'This test has not been implemented yet.'
        );
    }

    /**
     * @covers PHPUnit_GUI_HTML::_prepareResult
     * @todo   Implement test_prepareResult().
     */
    public function test_prepareResult() {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
                'This test has not been implemented yet.'
        );
    }

    /**
     * @covers PHPUnit_GUI_HTML::_prepareFailure
     * @todo   Implement test_prepareFailure().
     */
    public function test_prepareFailure() {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
                'This test has not been implemented yet.'
        );
    }

    /**
     * @covers PHPUnit_GUI_HTML::_preparePassedTests
     * @todo   Implement test_preparePassedTests().
     */
    public function test_preparePassedTests() {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
                'This test has not been implemented yet.'
        );
    }

    /**
     * @covers PHPUnit_GUI_HTML::_prepareError
     * @todo   Implement test_prepareError().
     */
    public function test_prepareError() {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
                'This test has not been implemented yet.'
        );
    }

}
