<?php

/**
 * Generated by PHPUnit_SkeletonGenerator 1.2.1 on 2014-08-09 at 08:18:20.
 */
class PHPUnit_GUI_SetupDecoratorTest extends PHPUnit_Framework_TestCase {

    /**
     * @var PHPUnit_GUI_SetupDecorator
     */
    protected $object;

    /**
     * Sets up the fixture, for example, opens a network connection.
     * This method is called before a test is executed.
     */
    protected function setUp() {
        $this->object = new PHPUnit_GUI_SetupDecorator;
    }

    /**
     * Tears down the fixture, for example, closes a network connection.
     * This method is called after a test is executed.
     */
    protected function tearDown() {
        
    }

    /**
     * @covers PHPUnit_GUI_SetupDecorator::show
     * @todo   Implement testShow().
     */
    public function testShow() {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
                'This test has not been implemented yet.'
        );
    }

    /**
     * @covers PHPUnit_GUI_SetupDecorator::getSuitesFromDir
     * @todo   Implement testGetSuitesFromDir().
     */
    public function testGetSuitesFromDir() {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
                'This test has not been implemented yet.'
        );
    }

    /**
     * @covers PHPUnit_GUI_SetupDecorator::_getFiles
     * @todo   Implement test_getFiles().
     */
    public function test_getFiles() {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
                'This test has not been implemented yet.'
        );
    }

}
