<?php

/**
 * Generated by PHPUnit_SkeletonGenerator 1.2.1 on 2014-08-09 at 08:18:24.
 */
class PHPUnit_AssertTest extends PHPUnit_Framework_TestCase {

    /**
     * @var PHPUnit_Assert
     */
    protected $object;

    /**
     * Sets up the fixture, for example, opens a network connection.
     * This method is called before a test is executed.
     */
    protected function setUp() {
        $this->object = new PHPUnit_Assert;
    }

    /**
     * Tears down the fixture, for example, closes a network connection.
     * This method is called after a test is executed.
     */
    protected function tearDown() {
        
    }

    /**
     * @covers PHPUnit_Assert::assertContains
     * @todo   Implement testAssertContains().
     */
    public function testAssertContains() {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
                'This test has not been implemented yet.'
        );
    }

    /**
     * @covers PHPUnit_Assert::assertNotContains
     * @todo   Implement testAssertNotContains().
     */
    public function testAssertNotContains() {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
                'This test has not been implemented yet.'
        );
    }

    /**
     * @covers PHPUnit_Assert::assertEquals
     * @todo   Implement testAssertEquals().
     */
    public function testAssertEquals() {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
                'This test has not been implemented yet.'
        );
    }

    /**
     * @covers PHPUnit_Assert::assertSame
     * @todo   Implement testAssertSame().
     */
    public function testAssertSame() {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
                'This test has not been implemented yet.'
        );
    }

    /**
     * @covers PHPUnit_Assert::assertNotSame
     * @todo   Implement testAssertNotSame().
     */
    public function testAssertNotSame() {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
                'This test has not been implemented yet.'
        );
    }

    /**
     * @covers PHPUnit_Assert::assertNotNull
     * @todo   Implement testAssertNotNull().
     */
    public function testAssertNotNull() {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
                'This test has not been implemented yet.'
        );
    }

    /**
     * @covers PHPUnit_Assert::assertNull
     * @todo   Implement testAssertNull().
     */
    public function testAssertNull() {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
                'This test has not been implemented yet.'
        );
    }

    /**
     * @covers PHPUnit_Assert::assertTrue
     * @todo   Implement testAssertTrue().
     */
    public function testAssertTrue() {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
                'This test has not been implemented yet.'
        );
    }

    /**
     * @covers PHPUnit_Assert::assertFalse
     * @todo   Implement testAssertFalse().
     */
    public function testAssertFalse() {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
                'This test has not been implemented yet.'
        );
    }

    /**
     * @covers PHPUnit_Assert::assertRegExp
     * @todo   Implement testAssertRegExp().
     */
    public function testAssertRegExp() {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
                'This test has not been implemented yet.'
        );
    }

    /**
     * @covers PHPUnit_Assert::assertNotRegExp
     * @todo   Implement testAssertNotRegExp().
     */
    public function testAssertNotRegExp() {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
                'This test has not been implemented yet.'
        );
    }

    /**
     * @covers PHPUnit_Assert::assertType
     * @todo   Implement testAssertType().
     */
    public function testAssertType() {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
                'This test has not been implemented yet.'
        );
    }

    /**
     * @covers PHPUnit_Assert::_convertToString
     * @todo   Implement test_convertToString().
     */
    public function test_convertToString() {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
                'This test has not been implemented yet.'
        );
    }

    /**
     * @covers PHPUnit_Assert::setLooselyTyped
     * @todo   Implement testSetLooselyTyped().
     */
    public function testSetLooselyTyped() {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
                'This test has not been implemented yet.'
        );
    }

    /**
     * @covers PHPUnit_Assert::fail
     * @todo   Implement testFail().
     */
    public function testFail() {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
                'This test has not been implemented yet.'
        );
    }

}
