<?php

/**
 * Generated by PHPUnit_SkeletonGenerator 1.2.1 on 2014-08-09 at 08:18:26.
 */
class PHPUnit_SkeletonTest extends PHPUnit_Framework_TestCase {

    /**
     * @var PHPUnit_Skeleton
     */
    protected $object;

    /**
     * Sets up the fixture, for example, opens a network connection.
     * This method is called before a test is executed.
     */
    protected function setUp() {
        $this->object = new PHPUnit_Skeleton;
    }

    /**
     * Tears down the fixture, for example, closes a network connection.
     * This method is called after a test is executed.
     */
    protected function tearDown() {
        
    }

    /**
     * @covers PHPUnit_Skeleton::setConfigFile
     * @todo   Implement testSetConfigFile().
     */
    public function testSetConfigFile() {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
                'This test has not been implemented yet.'
        );
    }

    /**
     * @covers PHPUnit_Skeleton::createTestClass
     * @todo   Implement testCreateTestClass().
     */
    public function testCreateTestClass() {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
                'This test has not been implemented yet.'
        );
    }

    /**
     * @covers PHPUnit_Skeleton::_createDefinition
     * @todo   Implement test_createDefinition().
     */
    public function test_createDefinition() {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
                'This test has not been implemented yet.'
        );
    }

    /**
     * @covers PHPUnit_Skeleton::_createConstructor
     * @todo   Implement test_createConstructor().
     */
    public function test_createConstructor() {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
                'This test has not been implemented yet.'
        );
    }

    /**
     * @covers PHPUnit_Skeleton::_createSetUpTearDown
     * @todo   Implement test_createSetUpTearDown().
     */
    public function test_createSetUpTearDown() {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
                'This test has not been implemented yet.'
        );
    }

    /**
     * @covers PHPUnit_Skeleton::_createMethod
     * @todo   Implement test_createMethod().
     */
    public function test_createMethod() {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
                'This test has not been implemented yet.'
        );
    }

    /**
     * @covers PHPUnit_Skeleton::_finishClass
     * @todo   Implement test_finishClass().
     */
    public function test_finishClass() {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
                'This test has not been implemented yet.'
        );
    }

    /**
     * @covers PHPUnit_Skeleton::_createTest
     * @todo   Implement test_createTest().
     */
    public function test_createTest() {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
                'This test has not been implemented yet.'
        );
    }

    /**
     * @covers PHPUnit_Skeleton::writeTestClass
     * @todo   Implement testWriteTestClass().
     */
    public function testWriteTestClass() {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
                'This test has not been implemented yet.'
        );
    }

    /**
     * @covers PHPUnit_Skeleton::_handleErrors
     * @todo   Implement test_handleErrors().
     */
    public function test_handleErrors() {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
                'This test has not been implemented yet.'
        );
    }

}
