<?php

/**
 * Generated by PHPUnit_SkeletonGenerator 1.2.1 on 2014-08-09 at 08:18:23.
 */
class PHPUnit_TestListenerTest extends PHPUnit_Framework_TestCase {

    /**
     * @var PHPUnit_TestListener
     */
    protected $object;

    /**
     * Sets up the fixture, for example, opens a network connection.
     * This method is called before a test is executed.
     */
    protected function setUp() {
        $this->object = new PHPUnit_TestListener;
    }

    /**
     * Tears down the fixture, for example, closes a network connection.
     * This method is called after a test is executed.
     */
    protected function tearDown() {
        
    }

    /**
     * @covers PHPUnit_TestListener::addError
     * @todo   Implement testAddError().
     */
    public function testAddError() {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
                'This test has not been implemented yet.'
        );
    }

    /**
     * @covers PHPUnit_TestListener::addFailure
     * @todo   Implement testAddFailure().
     */
    public function testAddFailure() {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
                'This test has not been implemented yet.'
        );
    }

    /**
     * @covers PHPUnit_TestListener::endTest
     * @todo   Implement testEndTest().
     */
    public function testEndTest() {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
                'This test has not been implemented yet.'
        );
    }

    /**
     * @covers PHPUnit_TestListener::startTest
     * @todo   Implement testStartTest().
     */
    public function testStartTest() {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
                'This test has not been implemented yet.'
        );
    }

}
