<?php

/**
 * Generated by PHPUnit_SkeletonGenerator 1.2.1 on 2014-08-09 at 08:16:52.
 */
class MimeTypeTest extends PHPUnit_Framework_TestCase {

    /**
     * @var MimeType
     */
    protected $object;

    /**
     * Sets up the fixture, for example, opens a network connection.
     * This method is called before a test is executed.
     */
    protected function setUp() {
        $this->object = new MimeType;
    }

    /**
     * Tears down the fixture, for example, closes a network connection.
     * This method is called after a test is executed.
     */
    protected function tearDown() {
        
    }

    /**
     * @covers MimeType::GetMimeTypeByPath
     * @todo   Implement testGetMimeTypeByPath().
     */
    public function testGetMimeTypeByPath() {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
                'This test has not been implemented yet.'
        );
    }

    /**
     * @covers MimeType::GetMimeTypeByExtension
     * @todo   Implement testGetMimeTypeByExtension().
     */
    public function testGetMimeTypeByExtension() {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
                'This test has not been implemented yet.'
        );
    }

    /**
     * @covers MimeType::IsPathPicture
     * @todo   Implement testIsPathPicture().
     */
    public function testIsPathPicture() {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
                'This test has not been implemented yet.'
        );
    }

    /**
     * @covers MimeType::IsPathFlash
     * @todo   Implement testIsPathFlash().
     */
    public function testIsPathFlash() {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
                'This test has not been implemented yet.'
        );
    }

    /**
     * @covers MimeType::_check_path_by_extension
     * @todo   Implement test_check_path_by_extension().
     */
    public function test_check_path_by_extension() {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
                'This test has not been implemented yet.'
        );
    }

    /**
     * @covers MimeType::GetMimeArray
     * @todo   Implement testGetMimeArray().
     */
    public function testGetMimeArray() {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
                'This test has not been implemented yet.'
        );
    }

}
