<?php

/**
 * Generated by PHPUnit_SkeletonGenerator 1.2.1 on 2014-08-09 at 08:16:53.
 */
class TranslitTest extends PHPUnit_Framework_TestCase {

    /**
     * @var Translit
     */
    protected $object;

    /**
     * Sets up the fixture, for example, opens a network connection.
     * This method is called before a test is executed.
     */
    protected function setUp() {
        $this->object = new Translit;
    }

    /**
     * Tears down the fixture, for example, closes a network connection.
     * This method is called after a test is executed.
     */
    protected function tearDown() {
        
    }

    /**
     * @covers Translit::Encode
     * @todo   Implement testEncode().
     */
    public function testEncode() {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
                'This test has not been implemented yet.'
        );
    }

    /**
     * @covers Translit::ClearServiceCharacters
     * @todo   Implement testClearServiceCharacters().
     */
    public function testClearServiceCharacters() {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
                'This test has not been implemented yet.'
        );
    }

    /**
     * @covers Translit::EncodeAndClear
     * @todo   Implement testEncodeAndClear().
     */
    public function testEncodeAndClear() {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
                'This test has not been implemented yet.'
        );
    }

}
